import type {
  Asset,
  AssetAssignment,
  AssetAuditEvent,
  AssetCategory,
  AssetCategoryKey,
  AssetEvent,
  AssetLocation,
  AssetModel,
  AssetResponsibilityRow,
  FundingSource,
  HardwareStandard,
  InventoryCheck,
  InventoryDiscrepancy,
  LifecyclePolicy,
  PersonalSoftwareLicence,
  ProcurementPlanItem,
  ReferencePrice,
  ReplacementDecision,
  SoftwareProduct,
} from "./asset-types";
import { todayIso } from "./clock";

/**
 * Az alkalmazás „mai” dátuma: normál módban a helyi aktuális nap,
 * vezetőségi demómódban a determinisztikus 2026-09-01.
 */
export const TODAY = todayIso();
export const NEXT_FINANCIAL_YEAR = 2027;

export const ASSET_CATEGORIES: AssetCategory[] = [
  { key: "notebook", label: "Notebook", computerClass: true, policyKey: "pol-notebook" },
  { key: "asztali", label: "Asztali számítógép", computerClass: true, policyKey: "pol-asztali" },
  { key: "munkaallomas", label: "Munkaállomás", computerClass: true, policyKey: "pol-munkaallomas" },
  { key: "monitor", label: "Monitor", computerClass: false, policyKey: "pol-monitor" },
  { key: "tablet", label: "Tablet", computerClass: true, policyKey: "pol-mobil" },
  { key: "mobil", label: "Mobiltelefon", computerClass: true, policyKey: "pol-mobil" },
  { key: "dokkolo", label: "Dokkoló", computerClass: false, policyKey: "pol-periferia" },
  { key: "nyomtato", label: "Nyomtató / MFP", computerClass: false, policyKey: "pol-nyomtato" },
  { key: "periferia", label: "Speciális periféria", computerClass: false, policyKey: "pol-periferia" },
  { key: "kutatasi", label: "Kutatási IT eszköz", computerClass: true, policyKey: "pol-munkaallomas" },
  { key: "egyeb", label: "Egyéb eszköz", computerClass: false, policyKey: "pol-periferia" },
];

export const LIFECYCLE_POLICIES: LifecyclePolicy[] = [
  {
    key: "pol-notebook",
    label: "Notebook életciklus-politika",
    categoryKey: "notebook",
    minYears: 4,
    maxYears: 5,
    plannedYears: 5,
    note: "Kari IT eszközgazda által jóváhagyott politika, 2026. évi felülvizsgálattal.",
  },
  {
    key: "pol-asztali",
    label: "Asztali PC életciklus-politika",
    categoryKey: "asztali",
    minYears: 5,
    maxYears: 6,
    plannedYears: 6,
    note: "Irodai felhasználás mellett 6 év tervezett élettartam.",
  },
  {
    key: "pol-munkaallomas",
    label: "Nagy teljesítményű munkaállomás",
    categoryKey: "munkaallomas",
    minYears: 4,
    maxYears: 6,
    plannedYears: 5,
    note: "Terheléstől függő: számításigényes kutatói terhelés esetén 4 év.",
  },
  {
    key: "pol-monitor",
    label: "Monitor életciklus-politika",
    categoryKey: "monitor",
    minYears: 7,
    maxYears: 10,
    plannedYears: 8,
    note: "Meghibásodásig történő használat megengedett.",
  },
  {
    key: "pol-mobil",
    label: "Mobil eszköz életciklus-politika",
    categoryKey: "mobil",
    minYears: 3,
    maxYears: 5,
    plannedYears: 4,
    note: "Biztonsági frissítések elérhetőségéhez kötött.",
  },
  {
    key: "pol-nyomtato",
    label: "Nyomtató életciklus-politika",
    categoryKey: "nyomtato",
    minYears: 6,
    maxYears: 8,
    plannedYears: 7,
    note: "Oldalszám-terhelés alapján felülvizsgálandó.",
  },
  {
    key: "pol-periferia",
    label: "Periféria és dokkoló",
    categoryKey: "periferia",
    minYears: 5,
    maxYears: 8,
    plannedYears: 6,
    note: "Csatlakozási szabvány elavulása esetén korábbi csere.",
  },
];

export const FUNDING_SOURCES: FundingSource[] = [
  { id: "fs-kari", name: "Kari IT keret", type: "kari_keret" },
  { id: "fs-kozponti", name: "Központi egyetemi keret", type: "kozponti" },
  { id: "fs-palyazat", name: "Kutatási pályázati forrás", type: "palyazat" },
  { id: "fs-intezeti", name: "Intézeti saját keret", type: "intezeti" },
];

export const ASSET_LOCATIONS: AssetLocation[] = [
  // Dékáni Hivatal
  { id: "loc-dekani-1", building: "Központi épület", room: "Dékáni Hivatal 112.", kind: "iroda", orgUnitId: "ou-dekani", primaryUserIds: ["u-dekan"] },
  { id: "loc-dekani-2", building: "Központi épület", room: "Tárgyaló 118.", kind: "iroda", orgUnitId: "ou-dekani" },
  { id: "loc-dekani-3", building: "Központi épület", room: "Dékánhelyettesi iroda 114.", kind: "iroda", orgUnitId: "ou-dekani", primaryUserIds: ["u-feher"] },
  { id: "loc-dekani-4", building: "Központi épület", room: "Hivatalvezetői iroda 110.", kind: "iroda", orgUnitId: "ou-dekani", primaryUserIds: ["u-nagy"] },
  { id: "loc-dekani-5", building: "Központi épület", room: "Gazdasági vezetői iroda 121.", kind: "iroda", orgUnitId: "ou-dekani", primaryUserIds: ["u-gazdvez"] },
  { id: "loc-dekani-6", building: "Központi épület", room: "Beszerzési iroda 124.", kind: "iroda", orgUnitId: "ou-dekani", primaryUserIds: ["u-beszerzo", "u-farkas"] },
  { id: "loc-dekani-7", building: "Központi épület", room: "Szolgáltatási ügyfélszolgálat 105.", kind: "iroda", orgUnitId: "ou-dekani", primaryUserIds: ["u-horvath", "u-molnar"] },
  { id: "loc-dekani-8", building: "Központi épület", room: "Web és digitalizációs iroda 131.", kind: "iroda", orgUnitId: "ou-dekani", primaryUserIds: ["u-balogh", "u-nemeth"] },
  { id: "loc-dekani-9", building: "Központi épület", room: "Eszközmenedzsment iroda 128.", kind: "iroda", orgUnitId: "ou-dekani", primaryUserIds: ["u-kiss"] },

  // IT egység
  { id: "loc-it-1", building: "Központi épület", room: "IT szervizműhely 002.", kind: "muhely", orgUnitId: "ou-it", primaryUserIds: ["u-eszkozmgr"] },
  { id: "loc-it-2", building: "Központi épület", room: "IT eszközraktár 004.", kind: "muhely", orgUnitId: "ou-it" },

  // Élettani Intézet
  { id: "loc-elettani-1", building: "Elméleti Tömb", room: "Élettani Intézet 214.", kind: "iroda", orgUnitId: "ou-elettani", primaryUserIds: ["u-kovacs"] },
  { id: "loc-elettani-2", building: "Elméleti Tömb", room: "Élettani labor 03.", kind: "labor", orgUnitId: "ou-elettani" },
  { id: "loc-elettani-3", building: "Elméleti Tömb", room: "Intézetigazgatói iroda 210.", kind: "iroda", orgUnitId: "ou-elettani", primaryUserIds: ["u-szabo"] },
  { id: "loc-elettani-4", building: "Elméleti Tömb", room: "Élettani IT műhely 216.", kind: "muhely", orgUnitId: "ou-elettani", primaryUserIds: ["u-itref"] },

  // Anatómiai Intézet
  { id: "loc-anatomiai-1", building: "Anatómiai épület", room: "Oktatói szoba 21.", kind: "iroda", orgUnitId: "ou-anatomiai" },
  { id: "loc-anatomiai-2", building: "Anatómiai épület", room: "Gyakorlóterem A.", kind: "labor", orgUnitId: "ou-anatomiai" },
  { id: "loc-anatomiai-3", building: "Anatómiai épület", room: "Intézetigazgatói iroda 12.", kind: "iroda", orgUnitId: "ou-anatomiai", primaryUserIds: ["u-fekete"] },
  { id: "loc-anatomiai-4", building: "Anatómiai épület", room: "Preparáló műhely 05.", kind: "muhely", orgUnitId: "ou-anatomiai" },

  // Biokémiai Intézet
  { id: "loc-biokemiai-1", building: "Elméleti Tömb", room: "Biokémiai Intézet 305.", kind: "iroda", orgUnitId: "ou-biokemiai" },
  { id: "loc-biokemiai-2", building: "Elméleti Tömb", room: "Intézetigazgatói iroda 301.", kind: "iroda", orgUnitId: "ou-biokemiai", primaryUserIds: ["u-varga"] },
  { id: "loc-biokemiai-3", building: "Elméleti Tömb", room: "Analitikai labor 308.", kind: "labor", orgUnitId: "ou-biokemiai" },

  // Farmakológiai Intézet
  { id: "loc-farmakologiai-1", building: "Elméleti Tömb", room: "Farmakológia 402.", kind: "iroda", orgUnitId: "ou-farmakologiai" },
  { id: "loc-farmakologiai-2", building: "Elméleti Tömb", room: "Intézetigazgatói iroda 400.", kind: "iroda", orgUnitId: "ou-farmakologiai", primaryUserIds: ["u-toth"] },
  { id: "loc-farmakologiai-3", building: "Elméleti Tömb", room: "Farmakológiai labor 407.", kind: "labor", orgUnitId: "ou-farmakologiai" },

  // Oktatásszervezés
  { id: "loc-oktatas-1", building: "Központi épület", room: "Oktatásszervezés 007.", kind: "iroda", orgUnitId: "ou-oktatas", primaryUserIds: ["u-simon"] },
  { id: "loc-oktatas-2", building: "Központi épület", room: "Számítógépes labor 1.", kind: "labor", orgUnitId: "ou-oktatas" },

  // Kutatástámogatás
  { id: "loc-kutatas-1", building: "Kutatóház", room: "Kutatástámogatás 12.", kind: "iroda", orgUnitId: "ou-kutatas", primaryUserIds: ["u-lukacs"] },
  { id: "loc-kutatas-2", building: "Kutatóház", room: "Kutatási labor 07.", kind: "labor", orgUnitId: "ou-kutatas" },

  // Klinikai együttműködés
  { id: "loc-klinikai-1", building: "Klinikai Tömb", room: "Együttműködési iroda 4.", kind: "iroda", orgUnitId: "ou-klinikai" },
  { id: "loc-klinikai-2", building: "Klinikai Tömb", room: "Klinikai oktatólabor 9.", kind: "labor", orgUnitId: "ou-klinikai" },
];


const feat = (...f: string[]) => f;

export const ASSET_MODELS: AssetModel[] = [
  {
    key: "dell-latitude-7450",
    manufacturer: "Dell",
    model: "Latitude 7450",
    categoryKey: "notebook",
    standardKey: "std-office-notebook",
    referenceNewPrice: 520000,
    spec: {
      processor: { vendor: "Intel", name: "Core Ultra 7 155U", generation: "Meteor Lake (Core Ultra 1. generáció)", releaseYear: 2024, cores: 12 },
      memory: { capacityGb: 32, type: "LPDDR5x", generation: "DDR5", speed: "6400 MT/s", configuration: "onboard" },
      storage: { type: "NVMe SSD", capacity: "1 TB", configuration: "1 × 1 TB M.2" },
      os: "Windows 11 Enterprise",
      osVersion: "24H2 (26100)",
      architecture: "x86-64",
      gpu: "Intel Graphics (integrált)",
      network: "Wi-Fi 6E + 2.5 GbE dokkolón",
      features: feat("TPM 2.0", "BitLocker", "Ujjlenyomat-olvasó", "Thunderbolt 4"),
    },
  },
  {
    key: "dell-latitude-5540",
    manufacturer: "Dell",
    model: "Latitude 5540",
    categoryKey: "notebook",
    standardKey: "std-office-notebook",
    referenceNewPrice: 430000,
    spec: {
      processor: { vendor: "Intel", name: "Core i7-1355U", generation: "13. generáció (Raptor Lake)", releaseYear: 2023, cores: 10 },
      memory: { capacityGb: 16, type: "DDR5", generation: "DDR5", speed: "4800 MT/s", configuration: "1 × 16 GB SO-DIMM" },
      storage: { type: "NVMe SSD", capacity: "512 GB", configuration: "1 × 512 GB M.2" },
      os: "Windows 11 Enterprise",
      osVersion: "23H2 (22631)",
      architecture: "x86-64",
      gpu: "Intel Iris Xe",
      network: "Wi-Fi 6E",
      features: feat("TPM 2.0", "BitLocker", "Docking támogatás"),
    },
  },
  {
    key: "dell-latitude-5420",
    manufacturer: "Dell",
    model: "Latitude 5420",
    categoryKey: "notebook",
    standardKey: "std-office-notebook",
    referenceNewPrice: 340000,
    spec: {
      processor: { vendor: "Intel", name: "Core i5-1145G7", generation: "11. generáció (Tiger Lake)", releaseYear: 2021, cores: 4 },
      memory: { capacityGb: 8, type: "DDR4", generation: "DDR4", speed: "3200 MT/s", configuration: "1 × 8 GB SO-DIMM" },
      storage: { type: "NVMe SSD", capacity: "256 GB", configuration: "1 × 256 GB M.2" },
      os: "Windows 11 Pro",
      osVersion: "22H2 (22621)",
      architecture: "x86-64",
      gpu: "Intel Iris Xe",
      network: "Wi-Fi 6",
      features: feat("TPM 2.0", "BitLocker"),
    },
  },
  {
    key: "lenovo-t14-g4",
    manufacturer: "Lenovo",
    model: "ThinkPad T14 Gen 4",
    categoryKey: "notebook",
    standardKey: "std-power-notebook",
    referenceNewPrice: 560000,
    spec: {
      processor: { vendor: "AMD", name: "Ryzen 7 PRO 7840U", generation: "Zen 4 (7040 sorozat)", releaseYear: 2023, cores: 8 },
      memory: { capacityGb: 32, type: "LPDDR5", generation: "DDR5", speed: "6400 MT/s", configuration: "onboard" },
      storage: { type: "NVMe SSD", capacity: "1 TB", configuration: "1 × 1 TB M.2" },
      os: "Windows 11 Pro",
      osVersion: "24H2 (26100)",
      architecture: "x86-64",
      gpu: "AMD Radeon 780M",
      network: "Wi-Fi 6E + LTE",
      features: feat("TPM 2.0", "IR-kamera", "LTE modul"),
    },
  },
  {
    key: "macbook-pro-14-m3",
    manufacturer: "Apple",
    model: 'MacBook Pro 14" (M3)',
    categoryKey: "notebook",
    standardKey: "std-power-notebook",
    referenceNewPrice: 780000,
    spec: {
      processor: { vendor: "Apple", name: "Apple M3", generation: "Apple Silicon 3. generáció", releaseYear: 2023, cores: 8 },
      memory: { capacityGb: 18, type: "Unified", generation: "LPDDR5", speed: "6400 MT/s", configuration: "egyesített memória" },
      storage: { type: "SSD", capacity: "512 GB", configuration: "beépített" },
      os: "macOS Sonoma",
      osVersion: "14.6.1",
      architecture: "arm64",
      gpu: "Apple GPU (10 mag)",
      network: "Wi-Fi 6E",
      features: feat("Secure Enclave", "FileVault", "Touch ID"),
    },
  },
  {
    key: "hp-elitedesk-800-g9",
    manufacturer: "HP",
    model: "EliteDesk 800 G9 SFF",
    categoryKey: "asztali",
    standardKey: "std-office-desktop",
    referenceNewPrice: 380000,
    spec: {
      processor: { vendor: "Intel", name: "Core i5-13500", generation: "13. generáció (Raptor Lake)", releaseYear: 2023, cores: 14 },
      memory: { capacityGb: 16, type: "DDR5", generation: "DDR5", speed: "4800 MT/s", configuration: "2 × 8 GB DIMM" },
      storage: { type: "NVMe SSD", capacity: "512 GB", configuration: "1 × 512 GB M.2" },
      os: "Windows 11 Enterprise",
      osVersion: "23H2 (22631)",
      architecture: "x86-64",
      gpu: "Intel UHD 770",
      network: "1 GbE",
      features: feat("vPro távmenedzsment", "TPM 2.0"),
    },
  },
  {
    key: "hp-prodesk-600-g5",
    manufacturer: "HP",
    model: "ProDesk 600 G5",
    categoryKey: "asztali",
    standardKey: "std-office-desktop",
    referenceNewPrice: 250000,
    spec: {
      processor: { vendor: "Intel", name: "Core i5-9500", generation: "9. generáció (Coffee Lake-R)", releaseYear: 2019, cores: 6 },
      memory: { capacityGb: 8, type: "DDR4", generation: "DDR4", speed: "2666 MT/s", configuration: "1 × 8 GB DIMM" },
      storage: { type: "SATA SSD", capacity: "256 GB", configuration: "1 × 256 GB 2,5\"" },
      os: "Windows 10 Pro",
      osVersion: "22H2 (19045)",
      architecture: "x86-64",
      gpu: "Intel UHD 630",
      network: "1 GbE",
      features: feat("TPM 2.0"),
    },
  },
  {
    key: "dell-optiplex-7060",
    manufacturer: "Dell",
    model: "OptiPlex 7060",
    categoryKey: "asztali",
    standardKey: "std-office-desktop",
    referenceNewPrice: 230000,
    spec: {
      processor: { vendor: "Intel", name: "Core i5-8500", generation: "8. generáció (Coffee Lake)", releaseYear: 2018, cores: 6 },
      memory: { capacityGb: 8, type: "DDR4", generation: "DDR4", speed: "2666 MT/s", configuration: "2 × 4 GB DIMM" },
      storage: { type: "SATA HDD + SSD", capacity: "1 TB + 128 GB", configuration: "vegyes" },
      os: "Windows 10 Pro",
      osVersion: "22H2 (19045)",
      architecture: "x86-64",
      gpu: "Intel UHD 630",
      network: "1 GbE",
      features: feat("TPM 2.0"),
    },
  },
  {
    key: "dell-precision-5860",
    manufacturer: "Dell",
    model: "Precision 5860",
    categoryKey: "munkaallomas",
    standardKey: "std-hpc-workstation",
    referenceNewPrice: 2100000,
    spec: {
      processor: { vendor: "Intel", name: "Xeon w5-2455X", generation: "Sapphire Rapids", releaseYear: 2023, cores: 12 },
      memory: { capacityGb: 128, type: "ECC DDR5", generation: "DDR5", speed: "4800 MT/s", configuration: "4 × 32 GB ECC" },
      storage: { type: "NVMe SSD + HDD", capacity: "2 TB + 4 TB", configuration: "SSD rendszer + HDD adat" },
      os: "Windows 11 Pro for Workstations",
      osVersion: "24H2 (26100)",
      architecture: "x86-64",
      gpu: "NVIDIA RTX A4000",
      network: "10 GbE",
      features: feat("ECC memória", "GPU-gyorsított képfeldolgozás"),
    },
  },
  {
    key: "lenovo-p3-linux",
    manufacturer: "Lenovo",
    model: "ThinkStation P3",
    categoryKey: "munkaallomas",
    standardKey: "std-research-workstation",
    referenceNewPrice: 1450000,
    spec: {
      processor: { vendor: "Intel", name: "Core i9-13900K", generation: "13. generáció (Raptor Lake)", releaseYear: 2022, cores: 24 },
      memory: { capacityGb: 64, type: "DDR5", generation: "DDR5", speed: "5600 MT/s", configuration: "2 × 32 GB DIMM" },
      storage: { type: "NVMe SSD", capacity: "2 TB", configuration: "1 × 2 TB M.2" },
      os: "Ubuntu LTS",
      osVersion: "24.04.1 LTS",
      architecture: "x86-64",
      gpu: "NVIDIA RTX 4070",
      network: "2.5 GbE",
      features: feat("CUDA 12.4", "LUKS lemeztitkosítás", "Konténeres futtatókörnyezet"),
    },
  },
  {
    key: "hp-z4-g4",
    manufacturer: "HP",
    model: "Z4 G4 Workstation",
    categoryKey: "munkaallomas",
    standardKey: "std-research-workstation",
    referenceNewPrice: 980000,
    spec: {
      processor: { vendor: "Intel", name: "Xeon W-2123", generation: "Skylake-W", releaseYear: 2017, cores: 4 },
      memory: { capacityGb: 32, type: "ECC DDR4", generation: "DDR4", speed: "2666 MT/s", configuration: "4 × 8 GB ECC" },
      storage: { type: "SATA SSD + HDD", capacity: "512 GB + 2 TB", configuration: "vegyes" },
      os: "Windows 10 Pro for Workstations",
      osVersion: "22H2 (19045)",
      architecture: "x86-64",
      gpu: "NVIDIA Quadro P2000",
      network: "1 GbE",
      features: feat("ECC memória"),
    },
  },
  {
    key: "dell-p2422h",
    manufacturer: "Dell",
    model: "P2422H 24\"",
    categoryKey: "monitor",
    standardKey: "std-monitor-base",
    referenceNewPrice: 78000,
    spec: { display: '23,8" IPS, 1920×1080, 60 Hz', features: feat("Állítható magasság", "DisplayPort + HDMI") },
  },
  {
    key: "dell-u2723qe",
    manufacturer: "Dell",
    model: "UltraSharp U2723QE 27\"",
    categoryKey: "monitor",
    standardKey: "std-monitor-large",
    referenceNewPrice: 185000,
    spec: { display: '27" IPS Black, 3840×2160, 60 Hz', features: feat("USB-C dokkolás 90 W", "KVM") },
  },
  {
    key: "eizo-rx270",
    manufacturer: "EIZO",
    model: "RadiForce RX270",
    categoryKey: "monitor",
    standardKey: "std-monitor-large",
    referenceNewPrice: 890000,
    spec: { display: '21,3" orvosdiagnosztikai, 2 MP', features: feat("Kalibrált fényerő", "DICOM GSDF") },
  },
  {
    key: "ipad-pro-11-m2",
    manufacturer: "Apple",
    model: 'iPad Pro 11" (M2)',
    categoryKey: "tablet",
    standardKey: "std-tablet",
    referenceNewPrice: 420000,
    spec: {
      processor: { vendor: "Apple", name: "Apple M2", generation: "Apple Silicon 2. generáció", releaseYear: 2022, cores: 8 },
      memory: { capacityGb: 8, type: "Unified", generation: "LPDDR5", speed: "—", configuration: "egyesített" },
      storage: { type: "Flash", capacity: "256 GB", configuration: "beépített" },
      os: "iPadOS",
      osVersion: "17.6.1",
      architecture: "arm64",
      network: "Wi-Fi 6E + eSIM",
      features: feat("Face ID", "MDM felügyelet", "Apple Pencil"),
    },
  },
  {
    key: "samsung-a54",
    manufacturer: "Samsung",
    model: "Galaxy A54 5G",
    categoryKey: "mobil",
    standardKey: "std-tablet",
    referenceNewPrice: 145000,
    spec: {
      processor: { vendor: "Samsung", name: "Exynos 1380", generation: "2023-as középkategória", releaseYear: 2023, cores: 8 },
      memory: { capacityGb: 8, type: "LPDDR4X", generation: "LPDDR4", speed: "—", configuration: "beépített" },
      storage: { type: "UFS", capacity: "128 GB", configuration: "beépített" },
      os: "Android",
      osVersion: "14 (One UI 6.1)",
      architecture: "arm64",
      network: "5G",
      features: feat("MDM felügyelet", "Knox"),
    },
  },
  {
    key: "dell-wd19",
    manufacturer: "Dell",
    model: "WD19TB dokkoló",
    categoryKey: "dokkolo",
    standardKey: "std-dock",
    referenceNewPrice: 92000,
    spec: { network: "1 GbE", features: feat("Thunderbolt 3", "180 W tápellátás", "Dupla monitor kimenet") },
  },
  {
    key: "hp-laserjet-m430",
    manufacturer: "HP",
    model: "LaserJet MFP M430",
    categoryKey: "nyomtato",
    referenceNewPrice: 320000,
    spec: {
      os: "HP FutureSmart firmware",
      osVersion: "5.6.0.3",
      network: "1 GbE",
      features: feat("Hálózati nyomtatás", "Biztonságos PIN-es nyomtatás", "Duplex", "Szkennelés e-mailbe"),
    },
  },
  {
    key: "epson-ds530",
    manufacturer: "Epson",
    model: "WorkForce DS-530 szkenner",
    categoryKey: "periferia",
    referenceNewPrice: 135000,
    spec: { features: feat("Duplex ADF", "35 lap/perc", "Hálózati modul opcionális") },
  },
  {
    key: "epson-eb-l520",
    manufacturer: "Epson",
    model: "EB-L520U prezentációs projektor",
    categoryKey: "periferia",
    referenceNewPrice: 640000,
    spec: { display: "WUXGA lézer, 5200 lumen", network: "1 GbE", features: feat("Vezeték nélküli prezentáció") },
  },
  {
    key: "leica-dmi8-pc",
    manufacturer: "Leica",
    model: "DMi8 vezérlő PC",
    categoryKey: "kutatasi",
    referenceNewPrice: 1250000,
    spec: {
      processor: { vendor: "Intel", name: "Core i7-9700", generation: "9. generáció (Coffee Lake-R)", releaseYear: 2019, cores: 8 },
      memory: { capacityGb: 32, type: "DDR4", generation: "DDR4", speed: "2666 MT/s", configuration: "4 × 8 GB" },
      storage: { type: "SSD + HDD", capacity: "512 GB + 8 TB", configuration: "mérési adattár" },
      os: "Windows 10 IoT Enterprise LTSC",
      osVersion: "2019",
      architecture: "x86-64",
      gpu: "NVIDIA Quadro P1000",
      network: "1 GbE (izolált mérőhálózat)",
      features: feat("Mikroszkóp-vezérlés", "Gyártói szoftverkötöttség"),
    },
  },
];

export const HARDWARE_STANDARDS: HardwareStandard[] = [
  {
    key: "std-office-notebook",
    label: "Általános irodai notebook",
    categoryKey: "notebook",
    minSpec: { cpuGeneration: 2022, cores: 8, ramGb: 16, storage: "512 GB NVMe SSD" },
    preferredSpec: { cpu: "Intel Core Ultra 5/7 vagy AMD Ryzen 5/7 PRO", cores: 12, ramGb: 32, storage: "1 TB NVMe SSD" },
    lifecycleYears: 5,
    referencePriceId: "rp-office-notebook",
    approvedModels: ["dell-latitude-7450", "dell-latitude-5540", "lenovo-t14-g4"],
    userProfile: "Adminisztratív és oktatói munkatársak",
    intendedUse: "Irodai alkalmazások, oktatás, online értekezlet.",
  },
  {
    key: "std-power-notebook",
    label: "Emelt teljesítményű notebook",
    categoryKey: "notebook",
    minSpec: { cpuGeneration: 2023, cores: 8, ramGb: 32, storage: "1 TB NVMe SSD" },
    preferredSpec: { cpu: "Ryzen 7 PRO / Core Ultra 7 / Apple M3", cores: 12, ramGb: 32, storage: "1 TB NVMe SSD" },
    lifecycleYears: 5,
    referencePriceId: "rp-power-notebook",
    approvedModels: ["lenovo-t14-g4", "macbook-pro-14-m3"],
    userProfile: "Kutatók, vezetők, mobil adatelemzés",
    intendedUse: "Adatelemzés, prezentáció, mobil kutatómunka.",
  },
  {
    key: "std-office-desktop",
    label: "Általános asztali PC",
    categoryKey: "asztali",
    minSpec: { cpuGeneration: 2021, cores: 6, ramGb: 16, storage: "512 GB SSD" },
    preferredSpec: { cpu: "Intel Core i5 13. generáció", cores: 14, ramGb: 16, storage: "512 GB NVMe SSD" },
    lifecycleYears: 6,
    referencePriceId: "rp-office-desktop",
    approvedModels: ["hp-elitedesk-800-g9"],
    userProfile: "Adminisztráció, tanulmányi ügyintézés",
    intendedUse: "Ügyviteli rendszerek, irodai alkalmazások.",
  },
  {
    key: "std-teaching-workstation",
    label: "Oktatói munkaállomás",
    categoryKey: "asztali",
    minSpec: { cpuGeneration: 2021, cores: 6, ramGb: 16, storage: "512 GB SSD" },
    preferredSpec: { cpu: "Intel Core i5/i7 13. generáció", cores: 14, ramGb: 32, storage: "1 TB NVMe SSD" },
    lifecycleYears: 6,
    referencePriceId: "rp-office-desktop",
    approvedModels: ["hp-elitedesk-800-g9"],
    userProfile: "Oktatók, gyakorlati termek",
    intendedUse: "Oktatási anyagok, prezentáció, e-learning.",
  },
  {
    key: "std-research-workstation",
    label: "Kutatói munkaállomás",
    categoryKey: "munkaallomas",
    minSpec: { cpuGeneration: 2021, cores: 12, ramGb: 32, storage: "1 TB NVMe SSD" },
    preferredSpec: { cpu: "Core i9 / Ryzen 9 aktuális generáció", cores: 24, ramGb: 64, storage: "2 TB NVMe SSD" },
    lifecycleYears: 5,
    referencePriceId: "rp-research-workstation",
    approvedModels: ["lenovo-p3-linux"],
    userProfile: "Kutatók, adatelemzők",
    intendedUse: "Statisztika, képfeldolgozás, szimuláció.",
  },
  {
    key: "std-hpc-workstation",
    label: "Nagy teljesítményű workstation",
    categoryKey: "munkaallomas",
    minSpec: { cpuGeneration: 2022, cores: 12, ramGb: 64, storage: "2 TB NVMe SSD" },
    preferredSpec: { cpu: "Xeon w5 / Threadripper PRO", cores: 16, ramGb: 128, storage: "2 TB NVMe + 4 TB HDD" },
    lifecycleYears: 5,
    referencePriceId: "rp-hpc-workstation",
    approvedModels: ["dell-precision-5860"],
    userProfile: "Képalkotó és nagy adatigényű kutatócsoportok",
    intendedUse: "GPU-gyorsított képfeldolgozás, nagy adathalmazok.",
  },
  {
    key: "std-monitor-base",
    label: "Alap monitor",
    categoryKey: "monitor",
    minSpec: { cpuGeneration: 0, cores: 0, ramGb: 0, storage: "—" },
    preferredSpec: { cpu: "—", cores: 0, ramGb: 0, storage: '23,8" FHD IPS' },
    lifecycleYears: 8,
    referencePriceId: "rp-monitor-base",
    approvedModels: ["dell-p2422h"],
    userProfile: "Általános munkaállomás",
    intendedUse: "Irodai kétmonitoros munkakörnyezet.",
  },
  {
    key: "std-monitor-large",
    label: "Nagy méretű monitor",
    categoryKey: "monitor",
    minSpec: { cpuGeneration: 0, cores: 0, ramGb: 0, storage: "—" },
    preferredSpec: { cpu: "—", cores: 0, ramGb: 0, storage: '27" 4K IPS USB-C' },
    lifecycleYears: 8,
    referencePriceId: "rp-monitor-large",
    approvedModels: ["dell-u2723qe"],
    userProfile: "Adatelemzés, képfeldolgozás, vezetői munkakör",
    intendedUse: "Nagy felbontású, több ablakos munkavégzés.",
  },
  {
    key: "std-dock",
    label: "Dokkoló",
    categoryKey: "dokkolo",
    minSpec: { cpuGeneration: 0, cores: 0, ramGb: 0, storage: "—" },
    preferredSpec: { cpu: "—", cores: 0, ramGb: 0, storage: "USB-C / Thunderbolt 4, 2 monitor" },
    lifecycleYears: 6,
    referencePriceId: "rp-dock",
    approvedModels: ["dell-wd19"],
    userProfile: "Notebookos munkatársak",
    intendedUse: "Asztali munkakörnyezet notebookhoz.",
  },
  {
    key: "std-tablet",
    label: "Tablet / mobil eszköz",
    categoryKey: "tablet",
    minSpec: { cpuGeneration: 2021, cores: 6, ramGb: 6, storage: "128 GB" },
    preferredSpec: { cpu: "Apple M2 / aktuális Android SoC", cores: 8, ramGb: 8, storage: "256 GB" },
    lifecycleYears: 4,
    referencePriceId: "rp-tablet",
    approvedModels: ["ipad-pro-11-m2", "samsung-a54"],
    userProfile: "Terepi adatgyűjtés, vezetői mobilitás",
    intendedUse: "Mobil adatrögzítés, prezentáció, kommunikáció.",
  },
  {
    key: "std-mobile-phone",
    label: "Intézményi okostelefon",
    categoryKey: "mobil",
    minSpec: { cpuGeneration: 2023, cores: 6, ramGb: 6, storage: "128 GB" },
    preferredSpec: { cpu: "Aktuális generációs mobil SoC", cores: 8, ramGb: 8, storage: "256 GB" },
    lifecycleYears: 4,
    referencePriceId: "rp-mobile-phone",
    approvedModels: ["samsung-a54"],
    userProfile: "Intézményi mobilkommunikáció",
    intendedUse: "Hívás, e-mail, MDM-felügyelt mobilalkalmazások.",
  },
];

export const REFERENCE_PRICES: ReferencePrice[] = [
  { id: "rp-office-notebook", label: "Általános irodai notebook", categoryKey: "notebook", netPrice: 390000, vatRate: 0.27, priceDate: "2026-05-14", validUntil: "2027-05-14", source: "keretszerzodes", supplier: "Kari IT keretszerződés / 2026-03", note: "23 db-os lehívás alapján." },
  { id: "rp-power-notebook", label: "Emelt teljesítményű notebook", categoryKey: "notebook", netPrice: 610000, vatRate: 0.27, priceDate: "2026-02-03", validUntil: "2026-12-31", source: "intezmenyi_beszerzes", supplier: "2026. februári kari beszerzés" },
  { id: "rp-office-desktop", label: "Általános asztali PC", categoryKey: "asztali", netPrice: 305000, vatRate: 0.27, priceDate: "2026-04-22", validUntil: "2027-04-22", source: "keretszerzodes", supplier: "Egyetemi keretszerződés" },
  { id: "rp-research-workstation", label: "Kutatói munkaállomás", categoryKey: "munkaallomas", netPrice: 1180000, vatRate: 0.27, priceDate: "2025-11-08", validUntil: "2026-11-08", source: "intezmenyi_beszerzes", supplier: "2025. novemberi beszerzés", note: "Ár 9 hónapnál régebbi, felülvizsgálandó." },
  { id: "rp-hpc-workstation", label: "Nagy teljesítményű workstation", categoryKey: "munkaallomas", netPrice: 1950000, vatRate: 0.27, priceDate: "2026-06-30", validUntil: "2027-06-30", source: "piaci_becsles", supplier: "Gyártói listaár alapján becsült" },
  { id: "rp-monitor-base", label: "24\" monitor", categoryKey: "monitor", netPrice: 62000, vatRate: 0.27, priceDate: "2026-05-14", validUntil: "2027-05-14", source: "keretszerzodes", supplier: "Kari IT keretszerződés / 2026-03" },
  { id: "rp-monitor-large", label: "27\" 4K monitor", categoryKey: "monitor", netPrice: 95000, vatRate: 0.27, priceDate: "2026-05-14", validUntil: "2027-05-14", source: "keretszerzodes", supplier: "Kari IT keretszerződés / 2026-03" },
  { id: "rp-dock", label: "USB-C dokkoló", categoryKey: "dokkolo", netPrice: 74000, vatRate: 0.27, priceDate: "2026-01-19", validUntil: "2026-12-31", source: "tervezoi_ar", supplier: "Kézzel rögzített tervezési ár" },
  { id: "rp-tablet", label: "Tablet", categoryKey: "tablet", netPrice: 330000, vatRate: 0.27, priceDate: "2026-03-11", validUntil: "2027-03-11", source: "intezmenyi_beszerzes", supplier: "2026. márciusi beszerzés" },
  { id: "rp-mobile-phone", label: "Intézményi okostelefon", categoryKey: "mobil", netPrice: 118000, vatRate: 0.27, priceDate: "2026-04-08", validUntil: "2027-04-08", source: "keretszerzodes", supplier: "Kari mobil keretszerződés / 2026" },
  { id: "rp-printer", label: "Hálózati MFP nyomtató", categoryKey: "nyomtato", netPrice: 285000, vatRate: 0.27, priceDate: "2025-09-02", validUntil: "2026-09-02", source: "piaci_becsles", supplier: "Piaci becslés", note: "Régi árinformáció." },
];

export const SOFTWARE_PRODUCTS: SoftwareProduct[] = [
  { key: "sw-spss", name: "IBM SPSS Statistics", manufacturer: "IBM", category: "Statisztika", supportEnd: { "27.0": "2024-12-31", "28.0": "2025-12-31", "29.0": "2026-12-31", "30.0": "2028-06-30" } },
  { key: "sw-matlab", name: "MATLAB", manufacturer: "MathWorks", category: "Numerikus számítás", supportEnd: { R2021b: "2025-09-30", R2023b: "2026-09-30", R2024a: "2027-03-31" } },
  { key: "sw-prism", name: "GraphPad Prism", manufacturer: "Dotmatics", category: "Biostatisztika", supportEnd: { "9": "2025-12-31", "10": "2027-12-31" } },
  { key: "sw-endnote", name: "EndNote", manufacturer: "Clarivate", category: "Hivatkozáskezelés", supportEnd: { "20": "2025-06-30", "21": "2027-06-30" } },
  { key: "sw-atlasti", name: "ATLAS.ti", manufacturer: "Scientific Software", category: "Kvalitatív elemzés", supportEnd: { "23": "2026-10-31", "24": "2028-01-31" } },
  { key: "sw-imaris", name: "Imaris", manufacturer: "Oxford Instruments", category: "Képelemzés", supportEnd: { "9.9": "2026-03-31", "10.1": "2028-03-31" } },
  { key: "sw-acrobat", name: "Adobe Acrobat Pro", manufacturer: "Adobe", category: "Dokumentumkezelés", supportEnd: { "2023": "2026-06-30", "2024": "2027-06-30" } },
  { key: "sw-nvivo", name: "NVivo", manufacturer: "Lumivero", category: "Kvalitatív elemzés", supportEnd: { "14": "2027-09-30" } },
  { key: "sw-origin", name: "OriginPro", manufacturer: "OriginLab", category: "Adatvizualizáció", supportEnd: { "2022": "2025-12-31", "2024": "2027-12-31" } },
  { key: "sw-camtasia", name: "Camtasia", manufacturer: "TechSmith", category: "Oktatási videó", supportEnd: { "2023": "2026-09-30", "2024": "2027-09-30" } },
  { key: "sw-gsuite-stat", name: "Stata BE", manufacturer: "StataCorp", category: "Statisztika", supportEnd: { "17": "2026-05-31", "18": "2028-05-31" } },
  { key: "sw-labview", name: "LabVIEW", manufacturer: "NI", category: "Mérésvezérlés", supportEnd: { "2021": "2025-12-31", "2024": "2028-12-31" } },
];

/* ------------------------------------------------------------------ */
/* Determinisztikus generátor                                          */
/* ------------------------------------------------------------------ */

function mulberry32(seed: number) {
  let a = seed;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const rnd = mulberry32(20260811);
const pick = <T,>(arr: T[]): T => arr[Math.floor(rnd() * arr.length)]!;
const between = (min: number, max: number) => min + Math.floor(rnd() * (max - min + 1));

const UNIT_USERS: Record<string, string[]> = {
  "ou-dekani": ["u-nagy", "u-horvath", "u-balogh", "u-molnar", "u-simon"],
  "ou-elettani": ["u-kovacs", "u-szabo", "u-lukacs"],
  "ou-anatomiai": ["u-fekete", "u-farkas"],
  "ou-biokemiai": ["u-varga"],
  "ou-farmakologiai": ["u-toth"],
  "ou-oktatas": ["u-nemeth", "u-kiss"],
  "ou-kutatas": ["u-feher"],
  "ou-klinikai": ["u-fekete"],
};

const UNIT_LOCATIONS: Record<string, string[]> = {
  "ou-dekani": ["loc-dekani-1", "loc-dekani-2"],
  "ou-elettani": ["loc-elettani-1", "loc-elettani-2"],
  "ou-anatomiai": ["loc-anatomiai-1", "loc-anatomiai-2"],
  "ou-biokemiai": ["loc-biokemiai-1"],
  "ou-farmakologiai": ["loc-farmakologiai-1"],
  "ou-oktatas": ["loc-oktatas-1", "loc-oktatas-2"],
  "ou-kutatas": ["loc-kutatas-1"],
  "ou-klinikai": ["loc-klinikai-1"],
};

const INVENTORY_RESPONSIBLE: Record<string, string> = {
  "ou-dekani": "u-molnar",
  "ou-elettani": "u-lukacs",
  "ou-anatomiai": "u-farkas",
  "ou-biokemiai": "u-varga",
  "ou-farmakologiai": "u-toth",
  "ou-oktatas": "u-kiss",
  "ou-kutatas": "u-feher",
  "ou-klinikai": "u-fekete",
};

const PURPOSES: Record<AssetCategoryKey, string[]> = {
  notebook: ["Oktatási és adminisztratív munka", "Kutatási adatelemzés", "Mobil ügyintézés", "Vezetői munkavégzés"],
  asztali: ["Tanulmányi ügyintézés", "Oktatásszervezés", "Adminisztratív munkavégzés"],
  munkaallomas: ["Képfeldolgozás", "Statisztikai számítás", "Szimuláció és modellezés"],
  monitor: ["Munkaállomás kijelzője", "Kétmonitoros munkakörnyezet"],
  tablet: ["Terepi adatgyűjtés", "Oktatási demonstráció"],
  mobil: ["Munkahelyi kommunikáció"],
  dokkolo: ["Notebook asztali munkakörnyezete"],
  nyomtato: ["Egységszintű nyomtatás"],
  periferia: ["Dokumentumdigitalizálás", "Előadótermi prezentáció"],
  kutatasi: ["Mérőműszer vezérlése", "Mérési adatgyűjtés"],
  egyeb: ["Egyéb intézeti felhasználás"],
};

function iso(y: number, m: number, d: number) {
  return `${y}-${String(m).padStart(2, "0")}-${String(d).padStart(2, "0")}`;
}

function addYears(date: string, years: number) {
  const [y, m, d] = date.split("-").map(Number) as [number, number, number];
  return iso(y + years, m, d);
}

interface Blueprint {
  modelKey: string;
  usage: "szemelyi" | "kozos";
  count: number;
  yearFrom: number;
  yearTo: number;
  units: string[];
}

const BLUEPRINTS: Blueprint[] = [
  { modelKey: "dell-latitude-7450", usage: "szemelyi", count: 9, yearFrom: 2024, yearTo: 2026, units: ["ou-dekani", "ou-elettani", "ou-oktatas", "ou-kutatas"] },
  { modelKey: "dell-latitude-5540", usage: "szemelyi", count: 12, yearFrom: 2022, yearTo: 2023, units: ["ou-dekani", "ou-elettani", "ou-anatomiai", "ou-biokemiai", "ou-oktatas"] },
  { modelKey: "dell-latitude-5420", usage: "szemelyi", count: 14, yearFrom: 2020, yearTo: 2021, units: ["ou-dekani", "ou-elettani", "ou-anatomiai", "ou-farmakologiai", "ou-oktatas", "ou-klinikai"] },
  { modelKey: "lenovo-t14-g4", usage: "szemelyi", count: 6, yearFrom: 2023, yearTo: 2024, units: ["ou-kutatas", "ou-biokemiai", "ou-elettani"] },
  { modelKey: "macbook-pro-14-m3", usage: "szemelyi", count: 3, yearFrom: 2023, yearTo: 2024, units: ["ou-dekani", "ou-kutatas"] },
  { modelKey: "hp-elitedesk-800-g9", usage: "szemelyi", count: 8, yearFrom: 2023, yearTo: 2025, units: ["ou-oktatas", "ou-dekani", "ou-elettani"] },
  { modelKey: "hp-prodesk-600-g5", usage: "szemelyi", count: 11, yearFrom: 2019, yearTo: 2020, units: ["ou-oktatas", "ou-dekani", "ou-anatomiai", "ou-farmakologiai"] },
  { modelKey: "dell-optiplex-7060", usage: "szemelyi", count: 9, yearFrom: 2018, yearTo: 2019, units: ["ou-elettani", "ou-anatomiai", "ou-biokemiai", "ou-klinikai"] },
  { modelKey: "dell-precision-5860", usage: "szemelyi", count: 3, yearFrom: 2023, yearTo: 2025, units: ["ou-kutatas", "ou-elettani"] },
  { modelKey: "lenovo-p3-linux", usage: "szemelyi", count: 5, yearFrom: 2022, yearTo: 2024, units: ["ou-elettani", "ou-biokemiai", "ou-kutatas"] },
  { modelKey: "hp-z4-g4", usage: "szemelyi", count: 6, yearFrom: 2017, yearTo: 2019, units: ["ou-elettani", "ou-anatomiai", "ou-farmakologiai"] },
  { modelKey: "dell-p2422h", usage: "szemelyi", count: 18, yearFrom: 2019, yearTo: 2024, units: ["ou-dekani", "ou-elettani", "ou-oktatas", "ou-anatomiai", "ou-biokemiai"] },
  { modelKey: "dell-u2723qe", usage: "szemelyi", count: 7, yearFrom: 2023, yearTo: 2025, units: ["ou-kutatas", "ou-dekani", "ou-elettani"] },
  { modelKey: "ipad-pro-11-m2", usage: "szemelyi", count: 4, yearFrom: 2022, yearTo: 2024, units: ["ou-dekani", "ou-kutatas", "ou-oktatas"] },
  { modelKey: "samsung-a54", usage: "szemelyi", count: 5, yearFrom: 2023, yearTo: 2024, units: ["ou-dekani", "ou-klinikai", "ou-oktatas"] },
  { modelKey: "dell-wd19", usage: "szemelyi", count: 12, yearFrom: 2020, yearTo: 2024, units: ["ou-dekani", "ou-elettani", "ou-oktatas", "ou-kutatas"] },
  // közös használatú eszközök
  { modelKey: "hp-laserjet-m430", usage: "kozos", count: 7, yearFrom: 2019, yearTo: 2024, units: ["ou-dekani", "ou-elettani", "ou-anatomiai", "ou-oktatas", "ou-farmakologiai"] },
  { modelKey: "epson-ds530", usage: "kozos", count: 4, yearFrom: 2019, yearTo: 2023, units: ["ou-dekani", "ou-oktatas", "ou-klinikai"] },
  { modelKey: "epson-eb-l520", usage: "kozos", count: 4, yearFrom: 2018, yearTo: 2022, units: ["ou-oktatas", "ou-anatomiai", "ou-elettani"] },
  { modelKey: "hp-prodesk-600-g5", usage: "kozos", count: 8, yearFrom: 2019, yearTo: 2020, units: ["ou-oktatas", "ou-anatomiai"] },
  { modelKey: "dell-latitude-5420", usage: "kozos", count: 4, yearFrom: 2020, yearTo: 2021, units: ["ou-oktatas", "ou-dekani", "ou-klinikai"] },
  { modelKey: "ipad-pro-11-m2", usage: "kozos", count: 2, yearFrom: 2022, yearTo: 2023, units: ["ou-oktatas", "ou-kutatas"] },
  { modelKey: "eizo-rx270", usage: "kozos", count: 2, yearFrom: 2020, yearTo: 2022, units: ["ou-klinikai", "ou-anatomiai"] },
  { modelKey: "leica-dmi8-pc", usage: "kozos", count: 3, yearFrom: 2018, yearTo: 2021, units: ["ou-elettani", "ou-biokemiai", "ou-kutatas"] },
];

function buildAssets() {
  const assets: Asset[] = [];
  const assignments: AssetAssignment[] = [];
  const events: AssetEvent[] = [];
  let seq = 3100;

  for (const bp of BLUEPRINTS) {
    const model = ASSET_MODELS.find((m) => m.key === bp.modelKey)!;
    for (let i = 0; i < bp.count; i++) {
      seq += between(3, 17);
      const orgUnitId = pick(bp.units);
      const locationId = pick(UNIT_LOCATIONS[orgUnitId] ?? ["loc-dekani-1"]);
      const users = UNIT_USERS[orgUnitId] ?? ["u-kovacs"];
      const userId = pick(users);
      const year = between(bp.yearFrom, bp.yearTo);
      const month = between(1, 12);
      const purchaseDate = iso(year, month, between(2, 27));
      const commissionDate = iso(year, Math.min(12, month + (rnd() > 0.5 ? 1 : 0)), between(2, 27));
      const priceFactor = 0.82 + rnd() * 0.3;
      const purchaseValue = Math.round((model.referenceNewPrice * priceFactor) / 1000) * 1000;
      const warrantyYears = model.categoryKey === "monitor" ? 3 : rnd() > 0.6 ? 5 : 3;
      const id = `as-${seq}`;
      const inventoryNo = `PTE-AOK-IT-${String(seq).padStart(6, "0")}`;
      const asset: Asset = {
        id,
        inventoryNo,
        deviceId: `AOK-${model.categoryKey.slice(0, 2).toUpperCase()}-${seq}`,
        categoryKey: model.categoryKey,
        modelKey: model.key,
        serial: `${model.manufacturer.slice(0, 3).toUpperCase()}${between(100000, 999999)}`,
        usage: bp.usage,
        assignedUserId: bp.usage === "szemelyi" ? userId : undefined,
        custodianUserId: bp.usage === "kozos" ? (INVENTORY_RESPONSIBLE[orgUnitId] ?? "u-molnar") : undefined,
        inventoryResponsibleId: INVENTORY_RESPONSIBLE[orgUnitId] ?? "u-molnar",
        orgUnitId,
        locationId,
        purpose: pick(PURPOSES[model.categoryKey] ?? ["Intézeti felhasználás"]),
        purchaseDate,
        commissionDate,
        purchaseValue,
        fundingSourceId: pick(["fs-kari", "fs-kozponti", "fs-palyazat", "fs-intezeti"]),
        costCenter: `KH-${orgUnitId.replace("ou-", "").slice(0, 5).toUpperCase()}-${between(10, 99)}`,
        warrantyEnd: addYears(purchaseDate, warrantyYears),
        condition: year <= 2019 ? pick(["kopott", "jo", "hibas"]) : pick(["kifogastalan", "jo", "jo"]),
        active: true,
        reportedIssues: year <= 2019 ? between(0, 4) : between(0, 1),
        repairCount: year <= 2019 ? between(0, 3) : 0,
        businessCritical: model.categoryKey === "kutatasi" || rnd() > 0.85,
      };
      assets.push(asset);

      assignments.push({
        id: `aa-${id}-1`,
        assetId: id,
        userId: asset.assignedUserId,
        orgUnitId,
        from: commissionDate,
        role: bp.usage === "szemelyi" ? "hasznalo" : "custodian",
      });
      if (rnd() > 0.75 && bp.usage === "szemelyi") {
        const prevUser = pick(users.filter((u) => u !== userId).length ? users.filter((u) => u !== userId) : users);
        assignments.push({
          id: `aa-${id}-0`,
          assetId: id,
          userId: prevUser,
          orgUnitId,
          from: purchaseDate,
          to: commissionDate,
          role: "hasznalo",
          note: "Korábbi használó – belső átadás.",
        });
      }
      events.push({
        id: `ae-${id}-1`,
        assetId: id,
        at: purchaseDate,
        type: "letrehozas",
        actorId: "u-molnar",
        title: "Eszköz nyilvántartásba vétele",
        detail: `${model.manufacturer} ${model.model} · ${inventoryNo}`,
      });
      events.push({
        id: `ae-${id}-2`,
        assetId: id,
        at: commissionDate,
        type: "hozzarendeles",
        actorId: "u-horvath",
        title: bp.usage === "szemelyi" ? "Használóhoz rendelés" : "Egységhez rendelés",
        detail: bp.usage === "szemelyi" ? `Használó: ${userId}` : `Szervezeti egység: ${orgUnitId}`,
      });
      if (asset.repairCount > 0) {
        events.push({
          id: `ae-${id}-3`,
          assetId: id,
          at: addYears(purchaseDate, 3),
          type: "javitas",
          actorId: "u-horvath",
          title: "Javítás",
          detail: pick(["Akkumulátorcsere", "Tápegység csere", "Ventilátor tisztítás és pasztacsere", "Alaplapi hiba javítása"]),
          cost: between(15, 90) * 1000,
        });
      }
    }
  }
  return { assets, assignments, events };
}

const built = buildAssets();
export const ASSETS: Asset[] = built.assets;
export const ASSET_ASSIGNMENTS: AssetAssignment[] = built.assignments;
export const ASSET_EVENTS: AssetEvent[] = built.events;

const notebookOf = (userId: string) =>
  ASSETS.find((a) => a.assignedUserId === userId && (a.categoryKey === "notebook" || a.categoryKey === "munkaallomas" || a.categoryKey === "asztali"))?.id;

export const PERSONAL_LICENCES: PersonalSoftwareLicence[] = [
  {
    id: "lic-001",
    productKey: "sw-spss",
    purpose: "Klinikai vizsgálati adatok statisztikai elemzése",
    version: "29.0",
    licenceType: "Egyfelhasználós, névre szóló éves licenc",
    assignedUserId: "u-kovacs",
    orgUnitId: "ou-elettani",
    assetId: notebookOf("u-kovacs"),
    purchaseDate: "2025-10-01",
    purchaseValue: 285000,
    licenceStart: "2025-10-01",
    licenceEnd: "2026-09-30",
    renewalDate: "2026-09-15",
    annualCost: 285000,
    fundingSourceId: "fs-palyazat",
    costCenter: "KH-ELETT-21",
    softwareOwnerId: "u-balogh",
  },
  {
    id: "lic-002",
    productKey: "sw-prism",
    purpose: "Kísérleti eredmények grafikus feldolgozása",
    version: "10",
    licenceType: "Névre szóló előfizetés",
    assignedUserId: "u-kovacs",
    orgUnitId: "ou-elettani",
    assetId: notebookOf("u-kovacs"),
    purchaseDate: "2026-01-15",
    purchaseValue: 172000,
    licenceStart: "2026-01-15",
    licenceEnd: "2027-01-14",
    renewalDate: "2026-12-20",
    annualCost: 172000,
    fundingSourceId: "fs-palyazat",
    costCenter: "KH-ELETT-21",
    softwareOwnerId: "u-balogh",
  },
  {
    id: "lic-003",
    productKey: "sw-matlab",
    purpose: "Jelfeldolgozási modellek futtatása",
    version: "R2023b",
    licenceType: "Egyedi kutatói licenc (munkaállomáshoz kötött)",
    assignedUserId: "u-feher",
    orgUnitId: "ou-kutatas",
    assetId: notebookOf("u-feher"),
    purchaseDate: "2023-11-05",
    purchaseValue: 640000,
    licenceStart: "2023-11-05",
    annualCost: 128000,
    fundingSourceId: "fs-palyazat",
    costCenter: "KH-KUTAT-11",
    softwareOwnerId: "u-balogh",
    note: "Karbantartási díj évente.",
  },
  {
    id: "lic-004",
    productKey: "sw-imaris",
    purpose: "Konfokális mikroszkópos felvételek 3D elemzése",
    version: "9.9",
    licenceType: "Munkaállomáshoz kötött node-locked licenc",
    assignedUserId: "u-varga",
    orgUnitId: "ou-biokemiai",
    assetId: notebookOf("u-varga"),
    purchaseDate: "2022-04-12",
    purchaseValue: 2850000,
    licenceStart: "2022-04-12",
    licenceEnd: "2026-03-31",
    annualCost: 420000,
    fundingSourceId: "fs-palyazat",
    costCenter: "KH-BIOKE-32",
    softwareOwnerId: "u-balogh",
    note: "Egyszemélyes szakmai függőség – helyettesítés nem megoldott.",
  },
  {
    id: "lic-005",
    productKey: "sw-endnote",
    purpose: "Publikációs hivatkozáskezelés",
    version: "21",
    licenceType: "Névre szóló örökös licenc",
    assignedUserId: "u-szabo",
    orgUnitId: "ou-elettani",
    assetId: notebookOf("u-szabo"),
    purchaseDate: "2024-02-20",
    purchaseValue: 96000,
    licenceStart: "2024-02-20",
    annualCost: 0,
    fundingSourceId: "fs-intezeti",
    costCenter: "KH-ELETT-14",
    softwareOwnerId: "u-balogh",
  },
  {
    id: "lic-006",
    productKey: "sw-atlasti",
    purpose: "Kvalitatív oktatáskutatási interjúk kódolása",
    version: "23",
    licenceType: "Éves egyfelhasználós előfizetés",
    assignedUserId: "u-nemeth",
    orgUnitId: "ou-oktatas",
    assetId: notebookOf("u-nemeth"),
    purchaseDate: "2025-09-01",
    purchaseValue: 210000,
    licenceStart: "2025-09-01",
    licenceEnd: "2026-08-31",
    renewalDate: "2026-08-15",
    annualCost: 210000,
    fundingSourceId: "fs-kari",
    costCenter: "KH-OKTAT-08",
    softwareOwnerId: "u-balogh",
  },
  {
    id: "lic-007",
    productKey: "sw-acrobat",
    purpose: "Kari dokumentumok szerkesztése és aláírása",
    version: "2024",
    licenceType: "Névre szóló előfizetés",
    assignedUserId: "u-horvath",
    orgUnitId: "ou-dekani",
    assetId: notebookOf("u-horvath"),
    purchaseDate: "2026-03-01",
    purchaseValue: 78000,
    licenceStart: "2026-03-01",
    licenceEnd: "2027-02-28",
    renewalDate: "2027-02-01",
    annualCost: 78000,
    fundingSourceId: "fs-kari",
    costCenter: "KH-DEKAN-01",
    softwareOwnerId: "u-balogh",
  },
  {
    id: "lic-008",
    productKey: "sw-nvivo",
    purpose: "Hallgatói visszajelzések szövegelemzése",
    version: "14",
    licenceType: "Egyfelhasználós licenc",
    assignedUserId: "u-kiss",
    orgUnitId: "ou-oktatas",
    assetId: notebookOf("u-kiss"),
    purchaseDate: "2025-05-19",
    purchaseValue: 265000,
    licenceStart: "2025-05-19",
    licenceEnd: "2027-05-18",
    annualCost: 132500,
    fundingSourceId: "fs-kari",
    costCenter: "KH-OKTAT-08",
    softwareOwnerId: "u-balogh",
    reportedUnused: true,
  },
  {
    id: "lic-009",
    productKey: "sw-origin",
    purpose: "Mérési adatsorok vizualizációja",
    version: "2022",
    licenceType: "Munkaállomáshoz kötött licenc",
    assignedUserId: "u-toth",
    orgUnitId: "ou-farmakologiai",
    assetId: notebookOf("u-toth"),
    purchaseDate: "2022-06-30",
    purchaseValue: 380000,
    licenceStart: "2022-06-30",
    licenceEnd: "2025-12-31",
    annualCost: 0,
    fundingSourceId: "fs-intezeti",
    costCenter: "KH-FARMA-45",
    softwareOwnerId: "u-balogh",
  },
  {
    id: "lic-010",
    productKey: "sw-camtasia",
    purpose: "Oktatási videók vágása",
    version: "2024",
    licenceType: "Névre szóló előfizetés",
    assignedUserId: "u-farkas",
    orgUnitId: "ou-anatomiai",
    assetId: notebookOf("u-farkas"),
    purchaseDate: "2025-11-11",
    purchaseValue: 112000,
    licenceStart: "2025-11-11",
    licenceEnd: "2026-11-10",
    renewalDate: "2026-10-20",
    annualCost: 112000,
    fundingSourceId: "fs-intezeti",
    costCenter: "KH-ANATO-17",
    softwareOwnerId: "u-balogh",
  },
  {
    id: "lic-011",
    productKey: "sw-gsuite-stat",
    purpose: "Epidemiológiai adatelemzés",
    version: "17",
    licenceType: "Névre szóló licenc",
    assignedUserId: "u-fekete",
    orgUnitId: "ou-anatomiai",
    assetId: notebookOf("u-fekete"),
    purchaseDate: "2023-03-14",
    purchaseValue: 195000,
    licenceStart: "2023-03-14",
    licenceEnd: "2026-09-30",
    renewalDate: "2026-09-01",
    annualCost: 65000,
    fundingSourceId: "fs-palyazat",
    costCenter: "KH-ANATO-17",
    softwareOwnerId: "u-balogh",
  },
  {
    id: "lic-012",
    productKey: "sw-labview",
    purpose: "Élettani mérőrendszer vezérlése",
    version: "2021",
    licenceType: "Munkaállomáshoz kötött licenc",
    assignedUserId: "u-lukacs",
    orgUnitId: "ou-elettani",
    assetId: notebookOf("u-lukacs"),
    purchaseDate: "2021-08-23",
    purchaseValue: 720000,
    licenceStart: "2021-08-23",
    licenceEnd: "2025-12-31",
    annualCost: 0,
    fundingSourceId: "fs-palyazat",
    costCenter: "KH-ELETT-21",
    softwareOwnerId: "u-balogh",
    note: "Kizárólag egy munkatárs használja – kritikus mérési folyamat.",
  },
];

export const INITIAL_DISCREPANCIES: InventoryDiscrepancy[] = [
  {
    id: "dis-001",
    kind: "hibas_adat",
    assetId: ASSETS[4]?.id,
    reportedBy: "u-kovacs",
    at: "2026-07-28",
    description: "A nyilvántartott memória 8 GB, valójában 16 GB van az eszközben.",
    status: "nyitott",
  },
  {
    id: "dis-002",
    kind: "nincs_nalam",
    assetId: ASSETS[11]?.id,
    reportedBy: "u-nemeth",
    at: "2026-07-15",
    description: "Az eszközt tavaly átadtam az Oktatásszervezési Egységnek.",
    status: "vizsgalat_alatt",
    handledBy: "u-molnar",
  },
  {
    id: "dis-003",
    kind: "szoftver_nem_hasznalt",
    licenceId: "lic-008",
    reportedBy: "u-kiss",
    at: "2026-06-30",
    description: "A licencet a projekt lezárása óta nem használom.",
    status: "nyitott",
  },
];

export const INITIAL_CHECKS: InventoryCheck[] = [
  {
    id: "chk-001",
    assetId: ASSETS[0]?.id ?? "",
    cycle: "2026. évi leltár",
    userId: "u-kovacs",
    answer: "nalam_van_hasznalom",
    at: "2026-06-12",
    stage: "lezarva",
  },
  {
    id: "chk-002",
    assetId: ASSETS[6]?.id ?? "",
    cycle: "2026. évi leltár",
    userId: "u-szabo",
    answer: "nalam_van_nem_hasznalom",
    at: "2026-06-18",
    stage: "leltarfelelos_ellenorzes",
    comment: "Tartalék eszközként az intézetben maradt.",
  },
];

export const INITIAL_REPLACEMENT_DECISIONS: ReplacementDecision[] = [];

export const ASSET_RESPONSIBILITIES: AssetResponsibilityRow[] = [
  { key: "hasznalo", label: "Eszköz használója", description: "Az eszközt ténylegesen használó munkatárs; adategyeztetésre és eltérés jelzésére jogosult.", userIds: ["u-kovacs", "u-nemeth", "u-toth"] },
  { key: "leltarfelelos", label: "Leltárfelelős", description: "A szervezeti egység fizikai leltáradatainak megerősítéséért felelős.", userIds: ["u-molnar", "u-lukacs", "u-farkas"] },
  { key: "szervezeti_jovahagyo", label: "Szervezeti jóváhagyó", description: "Egységszintű eszköz- és csereigények jóváhagyása.", userIds: ["u-szabo", "u-nagy", "u-fekete"] },
  { key: "it_eszkozgazda", label: "IT eszközgazda", description: "Hardverstandardok és életciklus-politika gazdája.", userIds: ["u-horvath"] },
  { key: "szoftvergazda", label: "Szoftvergazda", description: "Személyhez kötött licencek nyilvántartása, megújítás előkészítése.", userIds: ["u-balogh"] },
  { key: "beszerzesi_felelos", label: "Beszerzési felelős", description: "Beszerzési terv és beszerzési státusz kezelése.", userIds: ["u-simon"] },
  { key: "gazdasagi_jovahagyo", label: "Gazdasági jóváhagyó", description: "Forrás és keret jóváhagyása a beszerzési tervhez.", userIds: ["u-nagy"] },
];

export const INITIAL_ASSET_AUDIT: AssetAuditEvent[] = [
  { id: "aud-001", at: "2026-07-02", actorId: "u-horvath", entity: "asset", entityId: ASSETS[0]?.id ?? "", action: "Műszaki adat módosítás", detail: "Operációs rendszer verzió frissítve." },
  { id: "aud-002", at: "2026-07-10", actorId: "u-balogh", entity: "licenc", entityId: "lic-001", action: "Licenc megújítás előkészítés", detail: "2026-09-30 lejárat, megújítási javaslat rögzítve." },
  { id: "aud-003", at: "2026-07-21", actorId: "u-simon", entity: "beszerzes", entityId: "pp-001", action: "Beszerzési terv tétel létrehozása", detail: "2027 Q1 – általános irodai notebook." },
];

/* Kiinduló beszerzési terv a következő gazdasági évre (2027) */
export const INITIAL_PROCUREMENT_ITEMS: ProcurementPlanItem[] = [
  {
    id: "pp-001",
    planYear: NEXT_FINANCIAL_YEAR,
    quarter: "Q1",
    orgUnitId: "ou-dekani",
    replacedAssetIds: [],
    reason: "Életciklus-vég 2026 IV. – 2027 I. negyedév között",
    categoryKey: "notebook",
    standardKey: "std-office-notebook",
    quantity: 23,
    referencePriceId: "rp-office-notebook",
    priceChangePct: 4,
    contingencyPct: 5,
    quantityDiscountPct: 3,
    inflationPct: 3,
    priority: "magas",
    fundingSourceId: "fs-kari",
    status: "tervezett",
    kind: "csere",
    comment: "Kari szintű, összevont notebookcsere.",
  },
  {
    id: "pp-002",
    planYear: NEXT_FINANCIAL_YEAR,
    quarter: "Q2",
    orgUnitId: "ou-oktatas",
    replacedAssetIds: [],
    reason: "Elavult 24\" monitorok cseréje",
    categoryKey: "monitor",
    standardKey: "std-monitor-large",
    quantity: 18,
    referencePriceId: "rp-monitor-large",
    priceChangePct: 0,
    contingencyPct: 5,
    quantityDiscountPct: 2,
    inflationPct: 3,
    priority: "kozepes",
    fundingSourceId: "fs-kari",
    status: "tervezett",
    kind: "csere",
  },
  {
    id: "pp-003",
    planYear: NEXT_FINANCIAL_YEAR,
    quarter: "Q2",
    orgUnitId: "ou-elettani",
    replacedAssetIds: [],
    reason: "Támogatásból kifutott munkaállomások",
    categoryKey: "munkaallomas",
    standardKey: "std-research-workstation",
    quantity: 4,
    referencePriceId: "rp-research-workstation",
    priceChangePct: 8,
    contingencyPct: 10,
    quantityDiscountPct: 0,
    inflationPct: 3,
    priority: "kritikus",
    fundingSourceId: "fs-palyazat",
    status: "jovahagyasra_var",
    kind: "csere",
    comment: "Képfeldolgozási kapacitás fenntartása.",
  },
  {
    id: "pp-004",
    planYear: NEXT_FINANCIAL_YEAR,
    quarter: "Q3",
    orgUnitId: "ou-anatomiai",
    replacedAssetIds: [],
    reason: "Windows 10 támogatás megszűnése miatti asztali gépcsere",
    categoryKey: "asztali",
    standardKey: "std-office-desktop",
    quantity: 12,
    referencePriceId: "rp-office-desktop",
    priceChangePct: 2,
    contingencyPct: 5,
    quantityDiscountPct: 4,
    inflationPct: 3,
    priority: "magas",
    fundingSourceId: "fs-kozponti",
    status: "tervezett",
    kind: "csere",
  },
  {
    id: "pp-005",
    planYear: NEXT_FINANCIAL_YEAR,
    quarter: "Q4",
    orgUnitId: "ou-kutatas",
    replacedAssetIds: [],
    reason: "Új kutatócsoport eszközigénye",
    categoryKey: "notebook",
    standardKey: "std-power-notebook",
    quantity: 6,
    referencePriceId: "rp-power-notebook",
    priceChangePct: 5,
    contingencyPct: 8,
    quantityDiscountPct: 0,
    inflationPct: 3,
    priority: "kozepes",
    fundingSourceId: "fs-palyazat",
    status: "tervezett",
    kind: "uj_kapacitas",
  },
  {
    id: "pp-006",
    planYear: NEXT_FINANCIAL_YEAR,
    quarter: "Q3",
    orgUnitId: "ou-dekani",
    replacedAssetIds: [],
    reason: "Dokkolók cseréje az új notebookokhoz",
    categoryKey: "dokkolo",
    standardKey: "std-dock",
    quantity: 15,
    referencePriceId: "rp-dock",
    priceChangePct: 0,
    contingencyPct: 5,
    quantityDiscountPct: 5,
    inflationPct: 3,
    priority: "alacsony",
    fundingSourceId: "fs-kari",
    status: "tervezett",
    kind: "csere",
  },
];