import type { Product } from "./types";

/**
 * Kiegészítő katalógus – tablet, kijelző, projektor, periféria és nyomtató körök.
 * Besorolás: alkalmazotti = basic, vezetoi = átlagos, felsovezetoi = prémium.
 */
export const EXTRA_PRODUCTS_PERIPHERALS: Product[] = [
  // ── Tablet ─────────────────────────────────────────────────────────────
  {
    id: "prod-lenovo-tab-m11",
    categoryId: "pc-tablet",
    name: "Lenovo Tab M11 128GB",
    vendor: "Lenovo",
    tier: "alkalmazotti",
    referencePrice: 79000,
    active: true,
    spec: {
      os: "Android",
      osVersion: "Android 14",
      cpu: "MediaTek Helio G88 (8 mag)",
      ram: "4 GB",
      storage: "128 GB (microSD bővíthető)",
      display: '11" IPS, 1920×1200, 90 Hz, 400 nit',
      battery: "7040 mAh, kb. 10 óra",
      ports: "USB-C, 3,5 mm jack",
      warranty: "2 év gyártói garancia",
      features: ["Android Enterprise", "MDM felügyelet", "Tolltámogatás", "Wi-Fi 5", "Oktatási használatra"],
    },
  },
  {
    id: "prod-samsung-tab-a11-lte",
    categoryId: "pc-tablet",
    name: "Samsung Galaxy Tab A11+ 128GB LTE",
    vendor: "Samsung",
    tier: "alkalmazotti",
    referencePrice: 109000,
    active: true,
    spec: {
      os: "Android (One UI)",
      osVersion: "Android 15 / One UI 7",
      cpu: "MediaTek Dimensity 6300 (8 mag)",
      ram: "6 GB",
      storage: "128 GB (microSD bővíthető)",
      display: '11" TFT, 1920×1200, 90 Hz',
      battery: "7040 mAh, 25 W töltés",
      ports: "USB-C, nano SIM, 3,5 mm jack",
      warranty: "2 év gyártói garancia",
      features: ["LTE mobilnet", "Samsung Knox", "MDM felügyelet", "Vizitációs használatra", "Több felhasználós mód"],
    },
  },
  {
    id: "prod-ipad-a16",
    categoryId: "pc-tablet",
    name: 'Apple iPad 11" (A16) 128GB',
    vendor: "Apple",
    tier: "alkalmazotti",
    referencePrice: 189000,
    active: true,
    spec: {
      os: "iPadOS",
      osVersion: "18.6",
      cpu: "Apple A16 (6 mag)",
      ram: "6 GB",
      storage: "128 GB",
      display: '11" Liquid Retina, 2360×1640, 500 nit',
      battery: "28,93 Wh, kb. 10 óra",
      ports: "USB-C",
      warranty: "2 év AppleCare",
      features: ["Touch ID", "Apple Pencil (USB-C) támogatás", "MDM felügyelet", "Apple Business Manager", "Oktatási alkalmazások"],
    },
  },
  {
    id: "prod-xiaomi-pad-7",
    categoryId: "pc-tablet",
    name: "Xiaomi Pad 7 256GB",
    vendor: "Xiaomi",
    tier: "alkalmazotti",
    referencePrice: 149000,
    active: true,
    spec: {
      os: "Android (HyperOS)",
      osVersion: "Android 15 / HyperOS 2",
      cpu: "Snapdragon 7+ Gen 3 (8 mag)",
      ram: "8 GB",
      storage: "256 GB",
      display: '11,2" IPS, 3,2K, 144 Hz, 800 nit',
      battery: "8850 mAh, 45 W töltés",
      ports: "USB-C 3.2",
      warranty: "2 év gyártói garancia",
      features: ["Nagy felbontású kijelző", "Tolltámogatás", "MDM felügyelet", "Wi-Fi 6", "Prezentációhoz ajánlott"],
    },
  },
  {
    id: "prod-samsung-tab-active5",
    categoryId: "pc-tablet",
    name: "Samsung Galaxy Tab Active5 128GB (strapabíró)",
    vendor: "Samsung",
    tier: "vezetoi",
    referencePrice: 279000,
    active: true,
    spec: {
      os: "Android (One UI)",
      osVersion: "Android 15 / One UI 7",
      cpu: "Exynos 1380 (8 mag)",
      ram: "6 GB",
      storage: "128 GB (microSD bővíthető)",
      display: '8" TFT, 1920×1200, 600 nit',
      battery: "5050 mAh, cserélhető akkumulátor",
      ports: "USB-C, POGO dokk, 3,5 mm jack",
      warranty: "2 év gyártói garancia",
      features: ["IP68 és MIL-STD-810H", "Cserélhető akkumulátor", "Kesztyűs kezelés", "S Pen", "Klinikai és labor környezetbe"],
    },
  },
  {
    id: "prod-ipad-air-13-m3",
    categoryId: "pc-tablet",
    name: 'Apple iPad Air 13" (M3) 256GB',
    vendor: "Apple",
    tier: "vezetoi",
    referencePrice: 439000,
    active: true,
    spec: {
      os: "iPadOS",
      osVersion: "18.6",
      cpu: "Apple M3 (8 mag)",
      ram: "8 GB",
      storage: "256 GB",
      display: '13" Liquid Retina, 2732×2048, 600 nit',
      battery: "36,59 Wh, kb. 10 óra",
      ports: "USB-C (USB 3), eSIM opció",
      warranty: "2 év AppleCare",
      features: ["Touch ID", "Apple Pencil Pro támogatás", "MDM felügyelet", "Magic Keyboard támogatás", "Oktatói prezentációra"],
    },
  },
  {
    id: "prod-samsung-tab-s10-fe",
    categoryId: "pc-tablet",
    name: "Samsung Galaxy Tab S10 FE 256GB",
    vendor: "Samsung",
    tier: "vezetoi",
    referencePrice: 329000,
    active: true,
    spec: {
      os: "Android (One UI)",
      osVersion: "Android 15 / One UI 7",
      cpu: "Exynos 1580 (8 mag)",
      ram: "8 GB",
      storage: "256 GB (microSD bővíthető)",
      display: '10,9" IPS, 2304×1440, 90 Hz',
      battery: "8000 mAh, 45 W töltés",
      ports: "USB-C, POGO dokk",
      warranty: "2 év gyártói garancia",
      features: ["S Pen tartozék", "IP68", "Samsung Knox", "DeX mód", "MDM felügyelet"],
    },
  },
  {
    id: "prod-ipad-pro-13-m4",
    categoryId: "pc-tablet",
    name: 'Apple iPad Pro 13" (M4) 512GB',
    vendor: "Apple",
    tier: "felsovezetoi",
    referencePrice: 829000,
    active: true,
    spec: {
      os: "iPadOS",
      osVersion: "18.6",
      cpu: "Apple M4 (10 mag)",
      ram: "16 GB",
      storage: "512 GB",
      display: '13" Ultra Retina XDR OLED, 1600 nit csúcs, 120 Hz',
      battery: "38,99 Wh, kb. 10 óra",
      ports: "Thunderbolt / USB-C, eSIM",
      warranty: "2 év AppleCare",
      features: ["Face ID", "Apple Pencil Pro", "Neural Engine", "MDM felügyelet", "Reprezentációs használatra alkalmas"],
    },
  },
  {
    id: "prod-samsung-tab-s11-ultra",
    categoryId: "pc-tablet",
    name: "Samsung Galaxy Tab S11 Ultra 512GB",
    vendor: "Samsung",
    tier: "felsovezetoi",
    referencePrice: 789000,
    active: true,
    spec: {
      os: "Android (One UI)",
      osVersion: "Android 16 / One UI 8",
      cpu: "MediaTek Dimensity 9400+ (8 mag)",
      ram: "12 GB",
      storage: "512 GB (microSD bővíthető)",
      display: '14,6" Dynamic AMOLED 2X, 120 Hz, 1600 nit',
      battery: "11600 mAh, 45 W töltés",
      ports: "USB-C 3.2, POGO dokk",
      warranty: "2 év gyártói garancia",
      features: ["S Pen tartozék", "IP68", "DeX asztali mód", "Samsung Knox Vault", "Nagyméretű prezentációs kijelző"],
    },
  },
  {
    id: "prod-microsoft-surface-pro-11",
    categoryId: "pc-tablet",
    name: "Microsoft Surface Pro 11 (Copilot+ PC) 512GB",
    vendor: "Microsoft",
    tier: "felsovezetoi",
    referencePrice: 899000,
    active: true,
    spec: {
      os: "Windows 11 Pro",
      osVersion: "24H2 (build 26100.2314)",
      cpu: "Snapdragon X Elite (12 mag, 45 TOPS NPU)",
      ram: "16 GB LPDDR5X",
      storage: "512 GB NVMe SSD",
      display: '13" PixelSense OLED, 2880×1920, 120 Hz',
      battery: "53 Wh, kb. 14 óra",
      ports: "2× USB4, Surface Connect",
      warranty: "3 év kiterjesztett garancia",
      features: ["Copilot+ PC (NPU)", "Windows Hello arcfelismerés", "BitLocker titkosítás", "Levehető billentyűzet", "Intune felügyelet"],
    },
  },

  // ── Kijelző ────────────────────────────────────────────────────────────
  {
    id: "prod-dell-p2425h",
    categoryId: "pc-monitor",
    name: 'Dell P2425H 24" FHD monitor',
    vendor: "Dell",
    tier: "alkalmazotti",
    referencePrice: 62000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: '24" IPS, 1920×1200, 100 Hz, 250 nit',
      ports: "HDMI, DisplayPort, USB-C (adat), 4× USB-A hub",
      warranty: "3 év csereszolgáltatás",
      features: ["Állítható magasságú talp", "Pivot (álló mód)", "Villódzásmentes", "Kékfény-szűrő", "VESA rögzítés"],
    },
  },
  {
    id: "prod-hp-e24-g5",
    categoryId: "pc-monitor",
    name: 'HP E24 G5 24" FHD monitor',
    vendor: "HP",
    tier: "alkalmazotti",
    referencePrice: 58000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: '23,8" IPS, 1920×1080, 75 Hz, 250 nit',
      ports: "HDMI, DisplayPort, VGA, 4× USB-A hub",
      warranty: "3 év helyszíni garancia",
      features: ["Állítható magasságú talp", "Pivot", "Villódzásmentes", "Régi VGA forrásokhoz is", "VESA rögzítés"],
    },
  },
  {
    id: "prod-lenovo-t27h-30",
    categoryId: "pc-monitor",
    name: 'Lenovo ThinkVision T27h-30 27" QHD',
    vendor: "Lenovo",
    tier: "alkalmazotti",
    referencePrice: 118000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: '27" IPS, 2560×1440, 60 Hz, 350 nit',
      ports: "USB-C (75 W), HDMI, DisplayPort, RJ-45, USB hub",
      warranty: "3 év csereszolgáltatás",
      features: ["Beépített dokkoló", "Hálózati csatlakozás", "Egykábeles munkahely", "Alacsony kékfény", "VESA rögzítés"],
    },
  },
  {
    id: "prod-aoc-24b2xh",
    categoryId: "pc-monitor",
    name: 'AOC 24B2XH 24" FHD monitor',
    vendor: "AOC",
    tier: "alkalmazotti",
    referencePrice: 39000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: '23,8" IPS, 1920×1080, 75 Hz, 250 nit',
      ports: "HDMI, VGA",
      warranty: "3 év garancia",
      features: ["Keret nélküli dizájn", "Villódzásmentes", "Kékfény-szűrő", "Belépő irodai kijelző", "VESA rögzítés"],
    },
  },
  {
    id: "prod-philips-243b1",
    categoryId: "pc-monitor",
    name: 'Philips 243B1 24" FHD dokkoló monitor',
    vendor: "Philips",
    tier: "alkalmazotti",
    referencePrice: 74000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: '23,8" IPS, 1920×1080, 75 Hz, 250 nit',
      ports: "USB-C (65 W), HDMI, DisplayPort, RJ-45, 4× USB-A",
      warranty: "3 év garancia",
      features: ["Beépített dokkoló", "Hálózati csatlakozás", "PowerSensor energiatakarékosság", "Pivot", "VESA rögzítés"],
    },
  },
  {
    id: "prod-dell-u2724de",
    categoryId: "pc-monitor",
    name: 'Dell UltraSharp U2724DE 27" QHD dokkoló',
    vendor: "Dell",
    tier: "vezetoi",
    referencePrice: 189000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: '27" IPS Black, 2560×1440, 120 Hz, 350 nit',
      ports: "Thunderbolt 4 (90 W), HDMI, DisplayPort, RJ-45, USB hub",
      warranty: "3 év csereszolgáltatás",
      features: ["Thunderbolt dokkoló", "KVM funkció", "Hálózati csatlakozás", "Napellenző opció", "VESA rögzítés"],
    },
  },
  {
    id: "prod-hp-e34m-g4",
    categoryId: "pc-monitor",
    name: 'HP E34m G4 34" WQHD ívelt monitor',
    vendor: "HP",
    tier: "vezetoi",
    referencePrice: 265000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: '34" ívelt VA, 3440×1440, 100 Hz, 400 nit',
      ports: "USB-C (100 W), HDMI, DisplayPort, RJ-45, USB hub",
      warranty: "3 év helyszíni garancia",
      features: ["Ultraszéles képarány", "Beépített dokkoló", "Beépített hangszóró és kamera", "KVM funkció", "Videókonferenciára"],
    },
  },
  {
    id: "prod-lg-32un880",
    categoryId: "pc-monitor",
    name: 'LG 32UN880 32" 4K ergonómiai karos monitor',
    vendor: "LG",
    tier: "vezetoi",
    referencePrice: 235000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: '31,5" IPS, 3840×2160, 60 Hz, 350 nit',
      ports: "USB-C (60 W), 2× HDMI, DisplayPort, 2× USB-A",
      warranty: "2 év garancia",
      features: ["Beépített ergonómiai kar", "HDR10", "sRGB 95%", "Asztalra rögzíthető", "Egykábeles munkahely"],
    },
  },
  {
    id: "prod-dell-u4025qw",
    categoryId: "pc-monitor",
    name: 'Dell UltraSharp U4025QW 40" 5K ultraszéles',
    vendor: "Dell",
    tier: "felsovezetoi",
    referencePrice: 780000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: '39,7" ívelt IPS Black, 5120×2160, 120 Hz, 450 nit',
      ports: "Thunderbolt 4 (140 W), 2× HDMI, DisplayPort, RJ-45, USB hub",
      warranty: "3 év csereszolgáltatás",
      features: ["Két gép egyidejű kezelése (KVM)", "Thunderbolt dokkoló", "Beépített hangszóró", "Hálózati csatlakozás", "Vezetői munkaállomásra"],
    },
  },
  {
    id: "prod-apple-studio-display",
    categoryId: "pc-monitor",
    name: 'Apple Studio Display 27" 5K',
    vendor: "Apple",
    tier: "felsovezetoi",
    referencePrice: 749000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: '27" Retina 5K, 5120×2880, 600 nit, P3 színtér',
      ports: "Thunderbolt 3 (96 W), 3× USB-C",
      warranty: "3 év AppleCare for Enterprise",
      features: ["12 MP Center Stage kamera", "Hatszólamú hangrendszer", "Stúdiómikrofonok", "True Tone", "Reprezentációs használatra alkalmas"],
    },
  },

  // ── Projektor ──────────────────────────────────────────────────────────
  {
    id: "prod-epson-eb-e01",
    categoryId: "pc-projektor",
    name: "Epson EB-E01 oktatási projektor",
    vendor: "Epson",
    tier: "alkalmazotti",
    referencePrice: 119000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: "1024×768 (XGA), 3300 lumen",
      ports: "HDMI, VGA, kompozit",
      warranty: "3 év / 3 év lámpagarancia",
      features: ["Belépő tantermi projektor", "Egyszerű üzembe helyezés", "Hosszú lámpaélettartam (12 000 óra eco)", "Könnyű, hordozható", "Mennyezetre szerelhető"],
    },
  },
  {
    id: "prod-benq-mh550",
    categoryId: "pc-projektor",
    name: "BenQ MH550 Full HD projektor",
    vendor: "BenQ",
    tier: "alkalmazotti",
    referencePrice: 179000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: "1920×1080 (Full HD), 3500 lumen",
      ports: "2× HDMI, VGA, USB-A, RS-232",
      warranty: "3 év garancia",
      features: ["DLP technológia", "Nagy kontraszt (20 000:1)", "Automatikus trapézkorrekció", "Mennyezetre szerelhető", "Tantermi használatra"],
    },
  },
  {
    id: "prod-acer-x1529ki",
    categoryId: "pc-projektor",
    name: "Acer X1529Ki Full HD projektor",
    vendor: "Acer",
    tier: "alkalmazotti",
    referencePrice: 215000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: "1920×1080 (Full HD), 4500 lumen",
      ports: "2× HDMI, VGA, USB-A, RJ-45",
      warranty: "3 év garancia",
      features: ["Vezeték nélküli vetítés (WiFi dongle)", "Hálózati felügyelet", "Automatikus trapézkorrekció", "Nagy fényerő világos teremben", "Mennyezetre szerelhető"],
    },
  },
  {
    id: "prod-epson-eb-w52",
    categoryId: "pc-projektor",
    name: "Epson EB-W52 WXGA projektor",
    vendor: "Epson",
    tier: "alkalmazotti",
    referencePrice: 195000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: "1280×800 (WXGA), 4000 lumen",
      ports: "2× HDMI, VGA, USB-A, USB-B",
      warranty: "3 év / 3 év lámpagarancia",
      features: ["3LCD színazonos fényerő", "Kijelzőtükrözés USB-ről", "Split screen", "Zárható kábelfedél", "Tantermi rögzítés"],
    },
  },
  {
    id: "prod-optoma-hd146x",
    categoryId: "pc-projektor",
    name: "Optoma HD146X házimozi/oktatási projektor",
    vendor: "Optoma",
    tier: "alkalmazotti",
    referencePrice: 169000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: "1920×1080 (Full HD), 3600 lumen",
      ports: "HDMI 2.0, USB-A (tápellátás), 3,5 mm audio",
      warranty: "2 év garancia",
      features: ["DLP technológia", "Rec.709 színtér", "Alacsony késleltetés", "Kis méret", "Előadótermi bemutatókhoz"],
    },
  },
  {
    id: "prod-epson-eb-l570u",
    categoryId: "pc-projektor",
    name: "Epson EB-L570U WUXGA lézerprojektor",
    vendor: "Epson",
    tier: "vezetoi",
    referencePrice: 989000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: "1920×1200 (WUXGA), 5200 lumen",
      ports: "2× HDMI, HDBaseT, VGA, RJ-45, RS-232",
      warranty: "5 év / 20 000 óra",
      features: ["Lézer fényforrás", "Objektíveltolás", "Hálózati felügyelet és távvezérlés", "Karbantartásmentes működés", "Nagy előadóterembe"],
    },
  },
  {
    id: "prod-benq-lh730",
    categoryId: "pc-projektor",
    name: "BenQ LH730 Full HD lézerprojektor",
    vendor: "BenQ",
    tier: "vezetoi",
    referencePrice: 649000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: "1920×1080 (Full HD), 4000 lumen",
      ports: "2× HDMI, VGA, RJ-45, RS-232, USB-A",
      warranty: "5 év / 20 000 óra",
      features: ["Lézer fényforrás", "24/7 üzem", "360°-os telepítés", "Hálózati felügyelet", "Tárgyalótermi használatra"],
    },
  },
  {
    id: "prod-epson-eb-810e",
    categoryId: "pc-projektor",
    name: "Epson EB-810E ultra rövid vetítési távolságú lézerprojektor",
    vendor: "Epson",
    tier: "vezetoi",
    referencePrice: 1090000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: "1920×1080 (Full HD), 5000 lumen, 160\" kép 11 cm-ről",
      ports: "3× HDMI, VGA, RJ-45, USB-A",
      warranty: "5 év / 20 000 óra",
      features: ["Ultra rövid vetítési távolság", "Lézer fényforrás", "Vezeték nélküli vetítés", "Falra szerelhető", "Interaktív tantermi használatra"],
    },
  },
  {
    id: "prod-panasonic-pt-mz780",
    categoryId: "pc-projektor",
    name: "Panasonic PT-MZ780 WUXGA lézerprojektor",
    vendor: "Panasonic",
    tier: "felsovezetoi",
    referencePrice: 2290000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: "1920×1200 (WUXGA), 7000 lumen",
      ports: "2× HDMI, DVI-D, HDBaseT, RJ-45, RS-232",
      warranty: "5 év / 20 000 óra",
      features: ["Lézer fényforrás", "Porálló optikai blokk", "Geometriai korrekció és élösszemosás", "Központi hálózati felügyelet", "Aula és díszterem"],
    },
  },
  {
    id: "prod-epson-eb-pu1008b",
    categoryId: "pc-projektor",
    name: "Epson EB-PU1008B installációs lézerprojektor",
    vendor: "Epson",
    tier: "felsovezetoi",
    referencePrice: 4290000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: "1920×1200 (WUXGA), 8500 lumen",
      ports: "2× HDMI, DVI-D, SDI, HDBaseT, RJ-45",
      warranty: "5 év / 20 000 óra",
      features: ["Cserélhető objektívek", "4K javítás (4K Enhancement)", "Több projektor összehangolása", "24/7 installációs üzem", "Nagy aula és konferenciaközpont"],
    },
  },

  // ── Perifériák ─────────────────────────────────────────────────────────
  {
    id: "prod-logitech-mk270",
    categoryId: "pc-periferia",
    name: "Logitech MK270 vezeték nélküli szett",
    vendor: "Logitech",
    tier: "alkalmazotti",
    referencePrice: 12900,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: "—",
      battery: "AAA/AA elem, kb. 24 hónap billentyűzet-üzemidő",
      ports: "USB-A vevőegység (Unifying)",
      warranty: "3 év",
      features: ["Magyar kiosztás", "Numerikus billentyűzet", "Halk gombok", "Belépő irodai szett", "Plug and play"],
    },
  },
  {
    id: "prod-logitech-c920e",
    categoryId: "pc-periferia",
    name: "Logitech C920e HD webkamera",
    vendor: "Logitech",
    tier: "alkalmazotti",
    referencePrice: 24900,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: "1080p 30 fps videó",
      ports: "USB-A",
      warranty: "2 év",
      features: ["Automatikus fénykorrekció", "Kettős mikrofon", "Fizikai lencsevédő", "Teams és Zoom kompatibilis", "Online oktatáshoz"],
    },
  },
  {
    id: "prod-apc-back-ups-bx750",
    categoryId: "pc-periferia",
    name: "APC Back-UPS BX750MI szünetmentes tápegység",
    vendor: "APC",
    tier: "alkalmazotti",
    referencePrice: 44900,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: "LED állapotjelző",
      battery: "12 V zárt ólomakkumulátor, kb. 10 perc áthidalás",
      ports: "4× IEC kimenet, USB-B adat, RJ-45 túlfeszültségvédelem",
      warranty: "2 év (akkumulátorra 2 év)",
      features: ["750 VA / 410 W", "Túlfeszültségvédelem", "Automatikus leállítás szoftverrel", "Labor- és szervermunkahelyhez", "Cserélhető akkumulátor"],
    },
  },
  {
    id: "prod-logitech-b100",
    categoryId: "pc-periferia",
    name: "Logitech B100 vezetékes optikai egér",
    vendor: "Logitech",
    tier: "alkalmazotti",
    referencePrice: 3900,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: "—",
      ports: "USB-A",
      warranty: "3 év",
      features: ["800 dpi optikai érzékelő", "Kétkezes kialakítás", "Plug and play", "Belépő csereeszköz", "Tartós mikrokapcsolók"],
    },
  },
  {
    id: "prod-fujitsu-fi-8170",
    categoryId: "pc-periferia",
    name: "Ricoh fi-8170 dokumentumszkenner",
    vendor: "Ricoh (Fujitsu)",
    tier: "alkalmazotti",
    referencePrice: 289000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: "LCD kezelőpanel",
      ports: "USB 3.2, RJ-45",
      warranty: "3 év helyszíni",
      features: ["70 lap/perc kétoldalas szkennelés", "100 lapos adagoló", "Ultrahangos duplalap-érzékelés", "TWAIN/ISIS illesztő", "Iratdigitalizáláshoz"],
    },
  },
  {
    id: "prod-lenovo-usbc-dock-g2",
    categoryId: "pc-periferia",
    name: "Lenovo ThinkPad Universal USB-C dokkoló (100 W)",
    vendor: "Lenovo",
    tier: "vezetoi",
    referencePrice: 89000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: "Legfeljebb 3× 4K 60 Hz",
      ports: "USB-C, 2× DisplayPort, HDMI, RJ-45, 5× USB-A, 3,5 mm jack",
      warranty: "3 év",
      features: ["Notebook-töltés 100 W", "Gyártófüggetlen USB-C támogatás", "Wake on LAN", "MAC-cím áteresztés", "Egykábeles munkahely"],
    },
  },
  {
    id: "prod-jabra-evolve2-65-flex",
    categoryId: "pc-periferia",
    name: "Jabra Evolve2 65 Flex vezeték nélküli headset",
    vendor: "Jabra",
    tier: "vezetoi",
    referencePrice: 119000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: "—",
      battery: "kb. 20 óra beszélgetés",
      ports: "USB-C, Bluetooth 5.2, USB adapter",
      warranty: "2 év",
      features: ["Aktív zajszűrés (ANC)", "Microsoft Teams tanúsítvány", "Összehajtható kialakítás", "Több eszközhöz párosítható", "Videókonferenciára"],
    },
  },
  {
    id: "prod-logitech-mx-keys-combo",
    categoryId: "pc-periferia",
    name: "Logitech MX Keys S + MX Master 3S szett",
    vendor: "Logitech",
    tier: "vezetoi",
    referencePrice: 89000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: "—",
      battery: "Beépített akkumulátor, kb. 70 nap / 10 nap háttérvilágítással",
      ports: "USB-C töltés, Bluetooth LE, Logi Bolt vevő",
      warranty: "2 év",
      features: ["Csendes gombok és görgő", "Több gép közti váltás (Flow)", "Háttérvilágítás", "Ergonomikus kialakítás", "Titkosított Logi Bolt kapcsolat"],
    },
  },
  {
    id: "prod-logitech-rally-bar-mini",
    categoryId: "pc-periferia",
    name: "Logitech Rally Bar Mini videókonferencia-rendszer",
    vendor: "Logitech",
    tier: "felsovezetoi",
    referencePrice: 1290000,
    active: true,
    spec: {
      os: "CollabOS",
      osVersion: "1.12",
      cpu: "Beépített ARM vezérlő",
      ram: "4 GB",
      storage: "16 GB",
      display: "4K kamera, 5× zoom",
      ports: "HDMI be/ki, RJ-45, USB-C, USB-A",
      warranty: "3 év",
      features: ["Beépített MI-alapú képkivágás", "Teams és Zoom Rooms tanúsítvány", "Központi felügyelet (Logitech Sync)", "Beépített hangrendszer", "Kis és közepes tárgyalóba"],
    },
  },
  {
    id: "prod-wacom-cintiq-16",
    categoryId: "pc-periferia",
    name: 'Wacom Cintiq 16 rajzkijelző',
    vendor: "Wacom",
    tier: "felsovezetoi",
    referencePrice: 279000,
    active: true,
    spec: {
      os: "—",
      osVersion: "—",
      cpu: "—",
      ram: "—",
      storage: "—",
      display: '15,6" IPS, 1920×1080, 72% NTSC',
      ports: "HDMI, USB-A, USB-C (3-in-1 kábel)",
      warranty: "2 év",
      features: ["8192 nyomásszint (Pro Pen 2)", "Karcálló felület", "Állítható lábak", "Orvosi képi annotációhoz", "VESA rögzítés"],
    },
  },

  // ── Nyomtató ───────────────────────────────────────────────────────────
  {
    id: "prod-hp-laserjet-m209dwe",
    categoryId: "pc-nyomtato",
    name: "HP LaserJet M209dwe mono nyomtató",
    vendor: "HP",
    tier: "alkalmazotti",
    referencePrice: 69000,
    active: true,
    spec: {
      os: "HP firmware",
      osVersion: "20240515",
      cpu: "500 MHz beágyazott vezérlő",
      ram: "64 MB",
      storage: "—",
      display: "LED kezelőpanel",
      ports: "USB-B, Wi-Fi, Bluetooth LE",
      warranty: "2 év",
      features: ["29 lap/perc", "Automatikus duplex", "Wi-Fi nyomtatás", "Egyszemélyes irodába", "HP Smart Admin"],
    },
  },
  {
    id: "prod-brother-hl-l2445dw",
    categoryId: "pc-nyomtato",
    name: "Brother HL-L2445DW mono lézernyomtató",
    vendor: "Brother",
    tier: "alkalmazotti",
    referencePrice: 79000,
    active: true,
    spec: {
      os: "Brother firmware",
      osVersion: "1.24",
      cpu: "600 MHz beágyazott vezérlő",
      ram: "128 MB",
      storage: "—",
      display: "1 soros LCD",
      ports: "USB-B, RJ-45, Wi-Fi",
      warranty: "3 év helyszíni (regisztrációval)",
      features: ["36 lap/perc", "Automatikus duplex", "250 lapos tálca", "Hálózati nyomtatás", "Alacsony oldalköltség"],
    },
  },
  {
    id: "prod-canon-i-sensys-mf553dw",
    categoryId: "pc-nyomtato",
    name: "Canon i-SENSYS MF553dw multifunkciós nyomtató",
    vendor: "Canon",
    tier: "alkalmazotti",
    referencePrice: 249000,
    active: true,
    spec: {
      os: "Canon UFR II firmware",
      osVersion: "12.05",
      cpu: "1,2 GHz kétmagos vezérlő",
      ram: "1 GB",
      storage: "—",
      display: '5" érintőkijelző',
      ports: "RJ-45, USB-A, USB-B, Wi-Fi",
      warranty: "3 év helyszíni",
      features: ["43 lap/perc", "Duplex szkennelés", "Biztonságos PIN-es nyomtatás", "Szkennelés e-mailbe és SMB-re", "Munkacsoportos használat"],
    },
  },
  {
    id: "prod-epson-ecotank-et-4850",
    categoryId: "pc-nyomtato",
    name: "Epson EcoTank ET-4850 tintatartályos MFP",
    vendor: "Epson",
    tier: "alkalmazotti",
    referencePrice: 149000,
    active: true,
    spec: {
      os: "Epson firmware",
      osVersion: "SG12L4",
      cpu: "Beágyazott vezérlő",
      ram: "256 MB",
      storage: "—",
      display: '2,4" színes LCD',
      ports: "RJ-45, USB-B, Wi-Fi Direct",
      warranty: "3 év (regisztrációval)",
      features: ["Újratölthető tintatartály", "Nagyon alacsony oldalköltség", "ADF automatikus lapadagoló", "Duplex nyomtatás", "Színes dokumentumokhoz"],
    },
  },
  {
    id: "prod-brother-dcp-l3560cdw",
    categoryId: "pc-nyomtato",
    name: "Brother DCP-L3560CDW színes LED MFP",
    vendor: "Brother",
    tier: "alkalmazotti",
    referencePrice: 189000,
    active: true,
    spec: {
      os: "Brother firmware",
      osVersion: "1.18",
      cpu: "800 MHz beágyazott vezérlő",
      ram: "512 MB",
      storage: "—",
      display: '3,5" érintőkijelző',
      ports: "RJ-45, USB-B, Wi-Fi",
      warranty: "3 év helyszíni (regisztrációval)",
      features: ["26 lap/perc színes", "Automatikus duplex", "ADF lapadagoló", "Hálózati szkennelés", "Kisebb tanszéki irodába"],
    },
  },
  {
    id: "prod-hp-colorlaserjet-m480f",
    categoryId: "pc-nyomtato",
    name: "HP Color LaserJet Enterprise MFP M480f",
    vendor: "HP",
    tier: "vezetoi",
    referencePrice: 429000,
    active: true,
    spec: {
      os: "HP FutureSmart firmware",
      osVersion: "5.6.0.3",
      cpu: "1,2 GHz beágyazott vezérlő",
      ram: "2 GB",
      storage: "8 GB eMMC",
      display: '4,3" érintőkijelző',
      ports: "RJ-45, USB-A, USB-B",
      warranty: "3 év helyszíni",
      features: ["27 lap/perc színes", "HP Sure Start firmware-védelem", "Biztonságos PIN-es nyomtatás", "Szkennelés e-mailbe és SharePointra", "Központi flottamenedzsment"],
    },
  },
  {
    id: "prod-canon-imagerunner-c3226i",
    categoryId: "pc-nyomtato",
    name: "Canon imageRUNNER ADVANCE DX C3226i",
    vendor: "Canon",
    tier: "vezetoi",
    referencePrice: 1290000,
    active: true,
    spec: {
      os: "Canon imageWARE firmware",
      osVersion: "3.12",
      cpu: "Kétmagos 1,75 GHz vezérlő",
      ram: "3 GB",
      storage: "256 GB SSD",
      display: '10,1" érintőkijelző',
      ports: "RJ-45, USB-A, USB-B, opcionális Wi-Fi",
      warranty: "5 év szervizszerződéssel",
      features: ["26 lap/perc színes", "Kártyás azonosítás", "Titkosított tároló", "uniFLOW nyomtatásmenedzsment", "Folyosói közös nyomtatóhoz"],
    },
  },
  {
    id: "prod-kyocera-taskalfa-3554ci",
    categoryId: "pc-nyomtato",
    name: "Kyocera TASKalfa 3554ci színes MFP",
    vendor: "Kyocera",
    tier: "vezetoi",
    referencePrice: 1490000,
    active: true,
    spec: {
      os: "Kyocera HyPAS firmware",
      osVersion: "2.14",
      cpu: "1,2 GHz négymagos vezérlő",
      ram: "4 GB",
      storage: "32 GB SSD",
      display: '10,1" érintőkijelző',
      ports: "RJ-45, USB-A, USB-B",
      warranty: "5 év szervizszerződéssel",
      features: ["35 lap/perc színes", "Hosszú élettartamú dobegység", "Kártyás azonosítás", "Szkennelés hálózati mappába", "Alacsony fenntartási költség"],
    },
  },
  {
    id: "prod-hp-designjet-t650",
    categoryId: "pc-nyomtato",
    name: 'HP DesignJet T650 36" nagyformátumú plotter',
    vendor: "HP",
    tier: "felsovezetoi",
    referencePrice: 1690000,
    active: true,
    spec: {
      os: "HP firmware",
      osVersion: "24.1.5",
      cpu: "Beágyazott vezérlő",
      ram: "1 GB",
      storage: "—",
      display: '2,65" színes kezelőpanel',
      ports: "RJ-45, USB-B, Wi-Fi",
      warranty: "3 év helyszíni",
      features: ["A0 méretű nyomtatás", "Tekercsadagoló és automatikus vágó", "Poszter- és tervrajz-nyomtatás", "HP Click szoftver", "Konferencia-poszterekhez"],
    },
  },
  {
    id: "prod-epson-surecolor-sc-p700",
    categoryId: "pc-nyomtato",
    name: 'Epson SureColor SC-P700 A3+ fotónyomtató',
    vendor: "Epson",
    tier: "felsovezetoi",
    referencePrice: 449000,
    active: true,
    spec: {
      os: "Epson firmware",
      osVersion: "SP03L6",
      cpu: "Beágyazott vezérlő",
      ram: "512 MB",
      storage: "—",
      display: '4,3" érintőkijelző',
      ports: "RJ-45, USB-B, Wi-Fi",
      warranty: "3 év (regisztrációval)",
      features: ["10 tintás UltraChrome PRO10 rendszer", "A3+ méret", "Archív minőségű nyomat", "Szín- és feketefehér mód", "Tudományos publikációs ábrákhoz"],
    },
  },
];
