import type { Product } from "./types";

/**
 * Kiegészítő katalógus – számítástechnikai és mobil eszközkörök.
 * Besorolás: alkalmazotti = basic, vezetoi = átlagos, felsovezetoi = prémium.
 */
export const EXTRA_PRODUCTS_COMPUTING: Product[] = [
  // ── Notebook ───────────────────────────────────────────────────────────
  {
    id: "prod-hp-probook-450-g11",
    categoryId: "pc-notebook",
    name: 'HP ProBook 450 G11 (15,6" Intel)',
    vendor: "HP",
    tier: "alkalmazotti",
    referencePrice: 435000,
    active: true,
    spec: {
      os: "Windows 11 Pro",
      osVersion: "24H2 (build 26100.2314)",
      cpu: "Intel Core Ultra 5 125U (12 mag)",
      ram: "16 GB DDR5-5600",
      storage: "512 GB NVMe SSD",
      display: '15,6" FHD IPS, 250 nit, 16:9',
      battery: "51 Wh, kb. 9 óra",
      ports: "1× Thunderbolt 4, 2× USB-A, HDMI 2.1, RJ-45, 3,5 mm jack",
      warranty: "3 év helyszíni garancia",
      features: ["TPM 2.0", "BitLocker titkosítás", "HP Wolf Security", "Wi-Fi 6E", "Kamerazár", "Dokkolható"],
    },
  },
  {
    id: "prod-lenovo-v15-g4",
    categoryId: "pc-notebook",
    name: 'Lenovo V15 G4 IRU (15,6")',
    vendor: "Lenovo",
    tier: "alkalmazotti",
    referencePrice: 289000,
    active: true,
    spec: {
      os: "Windows 11 Pro",
      osVersion: "23H2 (build 22631.4460)",
      cpu: "Intel Core i5-1335U (10 mag)",
      ram: "16 GB DDR4-3200",
      storage: "512 GB NVMe SSD",
      display: '15,6" FHD TN, 250 nit',
      battery: "38 Wh, kb. 6 óra",
      ports: "1× USB-C, 2× USB-A, HDMI 1.4b, RJ-45, 3,5 mm jack",
      warranty: "2 év bevizsgálásos garancia",
      features: ["TPM 2.0", "BitLocker titkosítás", "Numerikus billentyűzet", "Wi-Fi 6", "Belépő adminisztratív munkára"],
    },
  },
  {
    id: "prod-acer-travelmate-p2-16",
    categoryId: "pc-notebook",
    name: 'Acer TravelMate P2 16 (P216-51)',
    vendor: "Acer",
    tier: "alkalmazotti",
    referencePrice: 349000,
    active: true,
    spec: {
      os: "Windows 11 Pro",
      osVersion: "24H2 (build 26100.2314)",
      cpu: "Intel Core i5-1335U (10 mag)",
      ram: "16 GB DDR4-3200",
      storage: "512 GB NVMe SSD",
      display: '16" WUXGA IPS, 300 nit, 16:10',
      battery: "50 Wh, kb. 8 óra",
      ports: "1× Thunderbolt 4, 2× USB-A, HDMI 2.1, RJ-45",
      warranty: "3 év hozd-be garancia",
      features: ["TPM 2.0", "Ujjlenyomat-olvasó", "MIL-STD-810H", "Wi-Fi 6E", "Kamerazár"],
    },
  },
  {
    id: "prod-dell-latitude-3550",
    categoryId: "pc-notebook",
    name: "Dell Latitude 3550 (2024)",
    vendor: "Dell",
    tier: "alkalmazotti",
    referencePrice: 398000,
    active: true,
    spec: {
      os: "Windows 11 Pro",
      osVersion: "24H2 (build 26100.2314)",
      cpu: "Intel Core 7 150U (10 mag)",
      ram: "16 GB DDR5-5200",
      storage: "512 GB NVMe SSD",
      display: '15,6" FHD IPS, 250 nit',
      battery: "54 Wh, kb. 9 óra",
      ports: "1× Thunderbolt 4, 2× USB-A, HDMI 2.0, RJ-45",
      warranty: "3 év ProSupport",
      features: ["TPM 2.0", "BitLocker titkosítás", "Dell Optimizer", "Wi-Fi 6E", "Dokkolható"],
    },
  },
  {
    id: "prod-asus-vivobook-16-oled",
    categoryId: "pc-notebook",
    name: 'ASUS Vivobook 16 OLED (M1605)',
    vendor: "ASUS",
    tier: "alkalmazotti",
    referencePrice: 329000,
    active: true,
    spec: {
      os: "Windows 11 Pro",
      osVersion: "23H2 (build 22631.4460)",
      cpu: "AMD Ryzen 5 7530U (6 mag)",
      ram: "16 GB DDR4-3200",
      storage: "512 GB NVMe SSD",
      display: '16" WUXGA OLED, 400 nit, 60 Hz',
      battery: "42 Wh, kb. 7 óra",
      ports: "1× USB-C, 2× USB-A, HDMI 1.4, microSD, 3,5 mm jack",
      warranty: "2 év gyártói garancia",
      features: ["OLED kijelző", "TPM 2.0", "Wi-Fi 6", "Ujjlenyomat-olvasó", "Oktatási prezentációhoz ajánlott"],
    },
  },
  {
    id: "prod-hp-elitebook-840-g11",
    categoryId: "pc-notebook",
    name: 'HP EliteBook 840 G11 (14" Core Ultra)',
    vendor: "HP",
    tier: "vezetoi",
    referencePrice: 785000,
    active: true,
    spec: {
      os: "Windows 11 Pro",
      osVersion: "24H2 (build 26100.2314)",
      cpu: "Intel Core Ultra 7 155U (12 mag)",
      ram: "32 GB DDR5-5600",
      storage: "1 TB NVMe SSD",
      display: '14" WUXGA IPS, 400 nit, 16:10',
      battery: "56 Wh, kb. 11 óra",
      ports: "2× Thunderbolt 4, 2× USB-A, HDMI 2.1, 3,5 mm jack",
      warranty: "3 év helyszíni garancia",
      features: ["TPM 2.0", "HP Sure Start", "IR-kamera (Windows Hello)", "Wi-Fi 7", "5 MP kamera", "Dokkolható"],
    },
  },
  {
    id: "prod-lenovo-x1-carbon-g12",
    categoryId: "pc-notebook",
    name: "Lenovo ThinkPad X1 Carbon Gen 12",
    vendor: "Lenovo",
    tier: "vezetoi",
    referencePrice: 995000,
    active: true,
    spec: {
      os: "Windows 11 Pro",
      osVersion: "24H2 (build 26100.2314)",
      cpu: "Intel Core Ultra 7 155H (16 mag, 34 TOPS NPU)",
      ram: "32 GB LPDDR5X-7467",
      storage: "1 TB NVMe SSD",
      display: '14" 2,8K OLED, 400 nit, 120 Hz',
      battery: "57 Wh, kb. 12 óra",
      ports: "2× Thunderbolt 4, 2× USB-A, HDMI 2.1",
      warranty: "3 év Premier Support",
      features: ["Copilot+ PC (NPU)", "TPM 2.0", "IR-kamera", "Wi-Fi 7", "1,09 kg tömeg", "MIL-STD-810H"],
    },
  },
  {
    id: "prod-dell-xps-14-9440",
    categoryId: "pc-notebook",
    name: "Dell XPS 14 (9440)",
    vendor: "Dell",
    tier: "vezetoi",
    referencePrice: 1150000,
    active: true,
    spec: {
      os: "Windows 11 Pro",
      osVersion: "24H2 (build 26100.2314)",
      cpu: "Intel Core Ultra 7 155H (16 mag)",
      ram: "32 GB LPDDR5X-6400",
      storage: "1 TB NVMe SSD",
      display: '14,5" 3,2K OLED érintő, 400 nit, 120 Hz',
      battery: "69,5 Wh, kb. 11 óra",
      ports: "3× Thunderbolt 4, microSD, 3,5 mm jack",
      warranty: "3 év ProSupport",
      features: ["NVIDIA RTX 4050 GPU", "Copilot+ képes NPU", "IR-kamera", "Wi-Fi 7", "CNC alumínium ház"],
    },
  },
  {
    id: "prod-macbook-air-15-m4",
    categoryId: "pc-notebook",
    name: 'Apple MacBook Air 15" (M4)',
    vendor: "Apple",
    tier: "felsovezetoi",
    referencePrice: 1290000,
    active: true,
    spec: {
      os: "macOS Sequoia",
      osVersion: "15.5",
      cpu: "Apple M4 (10 mag CPU / 10 mag GPU)",
      ram: "24 GB egyesített memória",
      storage: "1 TB SSD",
      display: '15,3" Liquid Retina, 500 nit',
      battery: "66,5 Wh, kb. 18 óra",
      ports: "2× Thunderbolt 4, MagSafe 3, 3,5 mm jack",
      warranty: "3 év AppleCare for Enterprise",
      features: ["Secure Enclave", "FileVault titkosítás", "Touch ID", "Neural Engine", "Passzív hűtés", "Reprezentációs használatra alkalmas"],
    },
  },
  {
    id: "prod-hp-zbook-firefly-14-g11",
    categoryId: "pc-notebook",
    name: 'HP ZBook Firefly 14 G11 mobil munkaállomás',
    vendor: "HP",
    tier: "felsovezetoi",
    referencePrice: 1390000,
    active: true,
    spec: {
      os: "Windows 11 Pro for Workstations",
      osVersion: "24H2 (build 26100.2314)",
      cpu: "Intel Core Ultra 7 165H vPro (16 mag)",
      ram: "64 GB DDR5-5600",
      storage: "2 TB NVMe SSD",
      display: '14" 2,8K OLED, 400 nit, 120 Hz',
      battery: "56 Wh, kb. 10 óra",
      ports: "2× Thunderbolt 4, 2× USB-A, HDMI 2.1, 3,5 mm jack",
      warranty: "3 év helyszíni, következő munkanapi",
      features: ["NVIDIA RTX A500 GPU", "ISV tanúsítás", "vPro távmenedzsment", "TPM 2.0", "Wi-Fi 7", "Kutatási adatfeldolgozásra"],
    },
  },

  // ── Asztali számítógép ─────────────────────────────────────────────────
  {
    id: "prod-lenovo-neo-50s-g4",
    categoryId: "pc-desktop",
    name: "Lenovo ThinkCentre neo 50s Gen 4 SFF",
    vendor: "Lenovo",
    tier: "alkalmazotti",
    referencePrice: 265000,
    active: true,
    spec: {
      os: "Windows 11 Pro",
      osVersion: "23H2 (build 22631.4460)",
      cpu: "Intel Core i5-13400 (10 mag)",
      ram: "16 GB DDR4-3200",
      storage: "512 GB NVMe SSD",
      display: "Nem tartozék",
      ports: "6× USB-A, 1× USB-C, DisplayPort, HDMI, RJ-45",
      warranty: "3 év helyszíni garancia",
      features: ["TPM 2.0", "BitLocker titkosítás", "Kettős monitor kimenet", "Kensington zár", "Adminisztratív munkahelyre"],
    },
  },
  {
    id: "prod-dell-optiplex-7020-sff",
    categoryId: "pc-desktop",
    name: "Dell OptiPlex 7020 SFF",
    vendor: "Dell",
    tier: "alkalmazotti",
    referencePrice: 315000,
    active: true,
    spec: {
      os: "Windows 11 Pro",
      osVersion: "24H2 (build 26100.2314)",
      cpu: "Intel Core i5-14500 (14 mag)",
      ram: "16 GB DDR5-4400",
      storage: "512 GB NVMe SSD",
      display: "Nem tartozék",
      ports: "8× USB-A, 1× USB-C, 2× DisplayPort, RJ-45",
      warranty: "3 év helyszíni garancia",
      features: ["TPM 2.0", "vPro távmenedzsment", "BitLocker titkosítás", "Szerszám nélküli bontás", "Energiatakarékos tápegység"],
    },
  },
  {
    id: "prod-hp-prodesk-400-g9-mt",
    categoryId: "pc-desktop",
    name: "HP Pro 400 G9 Microtower",
    vendor: "HP",
    tier: "alkalmazotti",
    referencePrice: 289000,
    active: true,
    spec: {
      os: "Windows 11 Pro",
      osVersion: "23H2 (build 22631.4460)",
      cpu: "Intel Core i5-13500 (14 mag)",
      ram: "16 GB DDR4-3200",
      storage: "512 GB NVMe SSD",
      display: "Nem tartozék",
      ports: "6× USB-A, 2× USB-C, DisplayPort, HDMI, RJ-45",
      warranty: "3 év helyszíni garancia",
      features: ["TPM 2.0", "HP Wolf Security", "Bővíthető ház", "Kettős monitor kimenet", "DVD-író opció"],
    },
  },
  {
    id: "prod-lenovo-m70q-g5-tiny",
    categoryId: "pc-desktop",
    name: "Lenovo ThinkCentre M70q Gen 5 Tiny",
    vendor: "Lenovo",
    tier: "alkalmazotti",
    referencePrice: 298000,
    active: true,
    spec: {
      os: "Windows 11 Pro",
      osVersion: "24H2 (build 26100.2314)",
      cpu: "Intel Core i5-14400T (10 mag)",
      ram: "16 GB DDR5-5600",
      storage: "512 GB NVMe SSD",
      display: "Nem tartozék",
      ports: "4× USB-A, 2× USB-C, DisplayPort, HDMI, RJ-45",
      warranty: "3 év helyszíni garancia",
      features: ["1 literes ház", "Monitor mögé szerelhető (VESA)", "TPM 2.0", "Halk működés", "Recepciós/labor pultra"],
    },
  },
  {
    id: "prod-asus-expertcenter-d700",
    categoryId: "pc-desktop",
    name: "ASUS ExpertCenter D700MD Tower",
    vendor: "ASUS",
    tier: "alkalmazotti",
    referencePrice: 275000,
    active: true,
    spec: {
      os: "Windows 11 Pro",
      osVersion: "23H2 (build 22631.4460)",
      cpu: "Intel Core i5-13400 (10 mag)",
      ram: "16 GB DDR4-3200",
      storage: "512 GB NVMe SSD + 1 TB HDD",
      display: "Nem tartozék",
      ports: "6× USB-A, 1× USB-C, DisplayPort, HDMI, VGA, RJ-45",
      warranty: "3 év helyszíni garancia",
      features: ["TPM 2.0", "Régi VGA kijelzőkhöz is csatlakoztatható", "Bővíthető tárhely", "Porszűrő", "Kensington zár"],
    },
  },
  {
    id: "prod-dell-optiplex-7020-plus",
    categoryId: "pc-desktop",
    name: "Dell OptiPlex 7020 Plus Tower",
    vendor: "Dell",
    tier: "vezetoi",
    referencePrice: 495000,
    active: true,
    spec: {
      os: "Windows 11 Pro",
      osVersion: "24H2 (build 26100.2314)",
      cpu: "Intel Core i7-14700 (20 mag)",
      ram: "32 GB DDR5-5600",
      storage: "1 TB NVMe SSD",
      display: "Nem tartozék",
      ports: "10× USB-A, 2× USB-C, 2× DisplayPort, RJ-45",
      warranty: "3 év ProSupport",
      features: ["vPro Enterprise", "TPM 2.0", "Bővítőkártya-helyek", "Kettős SSD támogatás", "Adatelemzési feladatokra"],
    },
  },
  {
    id: "prod-hp-elitedesk-800-g9-tower",
    categoryId: "pc-desktop",
    name: "HP Elite Tower 800 G9",
    vendor: "HP",
    tier: "vezetoi",
    referencePrice: 545000,
    active: true,
    spec: {
      os: "Windows 11 Enterprise",
      osVersion: "24H2 (build 26100.2314)",
      cpu: "Intel Core i7-14700 (20 mag)",
      ram: "32 GB DDR5-5600",
      storage: "1 TB NVMe SSD",
      display: "Nem tartozék",
      ports: "8× USB-A, 2× USB-C, 2× DisplayPort, HDMI, RJ-45",
      warranty: "3 év helyszíni garancia",
      features: ["HP Sure Start", "vPro távmenedzsment", "TPM 2.0", "Diszkrét GPU bővíthetőség", "Négy monitor támogatása"],
    },
  },
  {
    id: "prod-apple-mac-mini-m4",
    categoryId: "pc-desktop",
    name: "Apple Mac mini (M4)",
    vendor: "Apple",
    tier: "vezetoi",
    referencePrice: 549000,
    active: true,
    spec: {
      os: "macOS Sequoia",
      osVersion: "15.5",
      cpu: "Apple M4 (10 mag CPU / 10 mag GPU)",
      ram: "24 GB egyesített memória",
      storage: "512 GB SSD",
      display: "Nem tartozék",
      ports: "3× Thunderbolt 4, 2× USB-C, HDMI, RJ-45, 3,5 mm jack",
      warranty: "3 év AppleCare for Enterprise",
      features: ["Secure Enclave", "FileVault titkosítás", "Neural Engine", "Halk működés", "Kis helyigény"],
    },
  },
  {
    id: "prod-apple-imac-24-m4",
    categoryId: "pc-desktop",
    name: 'Apple iMac 24" (M4)',
    vendor: "Apple",
    tier: "felsovezetoi",
    referencePrice: 899000,
    active: true,
    spec: {
      os: "macOS Sequoia",
      osVersion: "15.5",
      cpu: "Apple M4 (10 mag CPU / 10 mag GPU)",
      ram: "24 GB egyesített memória",
      storage: "1 TB SSD",
      display: '23,5" 4,5K Retina, 500 nit',
      ports: "4× Thunderbolt 4, RJ-45, 3,5 mm jack",
      warranty: "3 év AppleCare for Enterprise",
      features: ["Beépített 4,5K kijelző", "Touch ID billentyűzet", "FileVault titkosítás", "12 MP Center Stage kamera", "Reprezentációs irodába"],
    },
  },
  {
    id: "prod-hp-z2-mini-g9",
    categoryId: "pc-desktop",
    name: "HP Z2 Mini G9 kompakt munkaállomás",
    vendor: "HP",
    tier: "felsovezetoi",
    referencePrice: 1120000,
    active: true,
    spec: {
      os: "Windows 11 Pro for Workstations",
      osVersion: "24H2 (build 26100.2314)",
      cpu: "Intel Core i9-13900 (24 mag)",
      ram: "64 GB DDR5-4800",
      storage: "2 TB NVMe SSD",
      display: "Nem tartozék",
      ports: "6× USB-A, 2× USB-C, 4× DisplayPort, RJ-45",
      warranty: "3 év helyszíni garancia",
      features: ["NVIDIA RTX A2000 GPU", "ISV tanúsítás", "2,7 literes ház", "TPM 2.0", "Négy 4K kijelző"],
    },
  },

  // ── Workstation ────────────────────────────────────────────────────────
  {
    id: "prod-dell-precision-3680",
    categoryId: "pc-workstation",
    name: "Dell Precision 3680 Tower",
    vendor: "Dell",
    tier: "alkalmazotti",
    referencePrice: 890000,
    active: true,
    spec: {
      os: "Windows 11 Pro for Workstations",
      osVersion: "24H2 (build 26100.2314)",
      cpu: "Intel Core i7-14700 (20 mag)",
      ram: "32 GB DDR5-4400",
      storage: "1 TB NVMe SSD",
      display: "Nem tartozék",
      ports: "8× USB-A, 2× USB-C, 4× DisplayPort, RJ-45",
      warranty: "3 év ProSupport",
      features: ["NVIDIA RTX A1000 GPU", "ISV tanúsítás", "TPM 2.0", "Belépő CAD és adatelemzés", "Bővíthető tápegység"],
    },
  },
  {
    id: "prod-hp-z2-tower-g9",
    categoryId: "pc-workstation",
    name: "HP Z2 Tower G9",
    vendor: "HP",
    tier: "alkalmazotti",
    referencePrice: 1050000,
    active: true,
    spec: {
      os: "Windows 11 Pro for Workstations",
      osVersion: "24H2 (build 26100.2314)",
      cpu: "Intel Core i7-14700K (20 mag)",
      ram: "64 GB DDR5-5600",
      storage: "1 TB NVMe SSD",
      display: "Nem tartozék",
      ports: "8× USB-A, 2× USB-C, DisplayPort, RJ-45",
      warranty: "3 év helyszíni garancia",
      features: ["NVIDIA RTX A2000 GPU", "ISV tanúsítás", "HP Remote Graphics", "TPM 2.0", "Képfeldolgozásra"],
    },
  },
  {
    id: "prod-lenovo-p3-tower-i7",
    categoryId: "pc-workstation",
    name: "Lenovo ThinkStation P3 Tower (i7)",
    vendor: "Lenovo",
    tier: "alkalmazotti",
    referencePrice: 980000,
    active: true,
    spec: {
      os: "Windows 11 Pro for Workstations",
      osVersion: "24H2 (build 26100.2314)",
      cpu: "Intel Core i7-14700 (20 mag)",
      ram: "64 GB DDR5-5600",
      storage: "1 TB NVMe SSD",
      display: "Nem tartozék",
      ports: "8× USB-A, 2× USB-C, 3× DisplayPort, RJ-45",
      warranty: "3 év helyszíni garancia",
      features: ["NVIDIA RTX A2000 GPU", "ISV tanúsítás", "Szerszám nélküli bontás", "TPM 2.0", "Statisztikai modellezésre"],
    },
  },
  {
    id: "prod-dell-precision-3591",
    categoryId: "pc-workstation",
    name: "Dell Precision 3591 mobil munkaállomás",
    vendor: "Dell",
    tier: "alkalmazotti",
    referencePrice: 1120000,
    active: true,
    spec: {
      os: "Windows 11 Pro for Workstations",
      osVersion: "24H2 (build 26100.2314)",
      cpu: "Intel Core Ultra 7 165H (16 mag)",
      ram: "32 GB DDR5-5600",
      storage: "1 TB NVMe SSD",
      display: '15,6" FHD+ IPS, 400 nit',
      battery: "64 Wh, kb. 8 óra",
      ports: "2× Thunderbolt 4, 2× USB-A, HDMI 2.1, RJ-45",
      warranty: "3 év ProSupport",
      features: ["NVIDIA RTX 500 Ada GPU", "ISV tanúsítás", "TPM 2.0", "Terepi adatgyűjtésre", "Dokkolható"],
    },
  },
  {
    id: "prod-lenovo-p5-xeon",
    categoryId: "pc-workstation",
    name: "Lenovo ThinkStation P5 (Xeon W)",
    vendor: "Lenovo",
    tier: "vezetoi",
    referencePrice: 2290000,
    active: true,
    spec: {
      os: "Windows 11 Pro for Workstations",
      osVersion: "24H2 (build 26100.2314)",
      cpu: "Intel Xeon w5-2465X (16 mag)",
      ram: "128 GB ECC DDR5",
      storage: "2 TB NVMe SSD",
      display: "Nem tartozék",
      ports: "10× USB-A, 2× USB-C, 4× DisplayPort, 10 GbE",
      warranty: "3 év helyszíni garancia",
      features: ["NVIDIA RTX 4500 Ada GPU", "ECC memória", "ISV tanúsítás", "TPM 2.0", "Orvosi képalkotás feldolgozására"],
    },
  },
  {
    id: "prod-hp-z4-g5",
    categoryId: "pc-workstation",
    name: "HP Z4 G5 munkaállomás",
    vendor: "HP",
    tier: "vezetoi",
    referencePrice: 2450000,
    active: true,
    spec: {
      os: "Ubuntu LTS",
      osVersion: "24.04.2 LTS (kernel 6.8)",
      cpu: "Intel Xeon w5-2455X (12 mag)",
      ram: "128 GB ECC DDR5",
      storage: "2 TB NVMe SSD + 8 TB HDD",
      display: "Nem tartozék",
      ports: "10× USB-A, 2× USB-C, 4× DisplayPort, 10 GbE",
      warranty: "3 év helyszíni garancia",
      features: ["NVIDIA RTX A4500 GPU", "CUDA 12.6", "LUKS lemeztitkosítás", "ECC memória", "Konténeres futtatókörnyezet"],
    },
  },
  {
    id: "prod-apple-mac-studio-m4max",
    categoryId: "pc-workstation",
    name: "Apple Mac Studio (M4 Max)",
    vendor: "Apple",
    tier: "vezetoi",
    referencePrice: 1690000,
    active: true,
    spec: {
      os: "macOS Sequoia",
      osVersion: "15.5",
      cpu: "Apple M4 Max (14 mag CPU / 32 mag GPU)",
      ram: "64 GB egyesített memória",
      storage: "1 TB SSD",
      display: "Nem tartozék",
      ports: "4× Thunderbolt 5, 2× USB-A, HDMI, SDXC, 10 GbE",
      warranty: "3 év AppleCare for Enterprise",
      features: ["Neural Engine", "FileVault titkosítás", "Videó- és képfeldolgozás", "Halk működés", "Négy 6K kijelző"],
    },
  },
  {
    id: "prod-dell-precision-7960",
    categoryId: "pc-workstation",
    name: "Dell Precision 7960 Tower",
    vendor: "Dell",
    tier: "felsovezetoi",
    referencePrice: 4890000,
    active: true,
    spec: {
      os: "Ubuntu LTS",
      osVersion: "24.04.2 LTS (kernel 6.8)",
      cpu: "Intel Xeon w7-3455 (24 mag)",
      ram: "256 GB ECC DDR5",
      storage: "4 TB NVMe SSD + 16 TB HDD",
      display: "Nem tartozék",
      ports: "12× USB-A, 4× USB-C, 4× DisplayPort, 2× 10 GbE",
      warranty: "5 év ProSupport Plus",
      features: ["NVIDIA RTX 6000 Ada GPU", "CUDA 12.6", "ECC memória", "Mélytanulási modellek tanítására", "Redundáns hűtés"],
    },
  },
  {
    id: "prod-lenovo-px-dual-xeon",
    categoryId: "pc-workstation",
    name: "Lenovo ThinkStation PX (dual Xeon)",
    vendor: "Lenovo",
    tier: "felsovezetoi",
    referencePrice: 6900000,
    active: true,
    spec: {
      os: "Ubuntu LTS",
      osVersion: "24.04.2 LTS (kernel 6.8)",
      cpu: "2× Intel Xeon Gold 6444Y (2× 16 mag)",
      ram: "512 GB ECC DDR5",
      storage: "8 TB NVMe SSD",
      display: "Nem tartozék",
      ports: "12× USB-A, 4× USB-C, 8× DisplayPort, 2× 10 GbE",
      warranty: "5 év helyszíni, 4 órás kiszállás",
      features: ["2× NVIDIA RTX 6000 Ada GPU", "ECC memória", "GPU-klaszter csomópont", "Genomikai és MI-kutatásra", "Rackbe szerelhető"],
    },
  },
  {
    id: "prod-hp-zbook-fury-16-g11",
    categoryId: "pc-workstation",
    name: 'HP ZBook Fury 16 G11 mobil munkaállomás',
    vendor: "HP",
    tier: "felsovezetoi",
    referencePrice: 2390000,
    active: true,
    spec: {
      os: "Windows 11 Pro for Workstations",
      osVersion: "24H2 (build 26100.2314)",
      cpu: "Intel Core i9-14900HX (24 mag)",
      ram: "128 GB DDR5-5600",
      storage: "4 TB NVMe SSD",
      display: '16" DreamColor 4K IPS, 600 nit',
      battery: "95 Wh, kb. 7 óra",
      ports: "2× Thunderbolt 4, 2× USB-A, HDMI 2.1, RJ-45, SD",
      warranty: "3 év helyszíni, következő munkanapi",
      features: ["NVIDIA RTX 3500 Ada GPU", "ISV tanúsítás", "Színhelyes kijelző", "TPM 2.0", "Konferencián is bemutatható"],
    },
  },

  // ── Okostelefon ────────────────────────────────────────────────────────
  {
    id: "prod-samsung-a17-5g",
    categoryId: "pc-okostelefon",
    name: "Samsung Galaxy A17 5G 128GB",
    vendor: "Samsung",
    tier: "alkalmazotti",
    referencePrice: 89000,
    active: true,
    spec: {
      os: "Android (One UI)",
      osVersion: "Android 15 / One UI 7",
      cpu: "Exynos 1330 (8 mag)",
      ram: "6 GB",
      storage: "128 GB (microSD bővíthető)",
      display: '6,7" Super AMOLED, 90 Hz, 800 nit',
      battery: "5000 mAh, 25 W töltés",
      ports: "USB-C, dual SIM",
      warranty: "2 év gyártói garancia",
      features: ["5G", "Samsung Knox", "NFC", "MDM felügyelet", "6 év biztonsági frissítés"],
    },
  },
  {
    id: "prod-motorola-g85",
    categoryId: "pc-okostelefon",
    name: "Motorola Moto G85 5G 256GB",
    vendor: "Motorola",
    tier: "alkalmazotti",
    referencePrice: 99000,
    active: true,
    spec: {
      os: "Android",
      osVersion: "Android 15",
      cpu: "Snapdragon 6s Gen 3 (8 mag)",
      ram: "8 GB",
      storage: "256 GB",
      display: '6,67" pOLED, 120 Hz, 1600 nit',
      battery: "5000 mAh, 30 W töltés",
      ports: "USB-C, dual SIM, 3,5 mm jack",
      warranty: "2 év gyártói garancia",
      features: ["5G", "IP52", "NFC", "Android Enterprise Recommended", "MDM felügyelet"],
    },
  },
  {
    id: "prod-nokia-xr21",
    categoryId: "pc-okostelefon",
    name: "Nokia XR21 5G strapabíró okostelefon",
    vendor: "Nokia (HMD)",
    tier: "alkalmazotti",
    referencePrice: 159000,
    active: true,
    spec: {
      os: "Android",
      osVersion: "Android 14",
      cpu: "Snapdragon 695 5G (8 mag)",
      ram: "6 GB",
      storage: "128 GB",
      display: '6,49" IPS, 120 Hz, 550 nit',
      battery: "4800 mAh, 33 W töltés",
      ports: "USB-C, dual SIM",
      warranty: "4 év gyártói garancia",
      features: ["IP69K por- és vízállóság", "MIL-STD-810H", "Programozható vészgomb", "5G", "Terepi és műhelyhasználatra"],
    },
  },
  {
    id: "prod-xiaomi-redmi-14c",
    categoryId: "pc-okostelefon",
    name: "Xiaomi Redmi 14C 128GB",
    vendor: "Xiaomi",
    tier: "alkalmazotti",
    referencePrice: 62000,
    active: true,
    spec: {
      os: "Android (HyperOS)",
      osVersion: "Android 14 / HyperOS 1",
      cpu: "MediaTek Helio G81-Ultra (8 mag)",
      ram: "4 GB",
      storage: "128 GB (microSD bővíthető)",
      display: '6,88" IPS, 120 Hz, 600 nit',
      battery: "5160 mAh, 18 W töltés",
      ports: "USB-C, dual SIM, 3,5 mm jack",
      warranty: "2 év gyártói garancia",
      features: ["Belépő intézményi készülék", "MDM felügyelet", "Dual SIM", "Nagy kijelző", "Ujjlenyomat-olvasó"],
    },
  },
  {
    id: "prod-samsung-a36-5g",
    categoryId: "pc-okostelefon",
    name: "Samsung Galaxy A36 5G 256GB",
    vendor: "Samsung",
    tier: "alkalmazotti",
    referencePrice: 139000,
    active: true,
    spec: {
      os: "Android (One UI)",
      osVersion: "Android 15 / One UI 7",
      cpu: "Snapdragon 6 Gen 3 (8 mag)",
      ram: "8 GB",
      storage: "256 GB",
      display: '6,7" Super AMOLED, 120 Hz, 1200 nit',
      battery: "5000 mAh, 45 W töltés",
      ports: "USB-C, dual SIM + eSIM",
      warranty: "2 év gyártói garancia",
      features: ["5G", "IP67", "Samsung Knox Suite", "NFC", "6 év szoftverfrissítés"],
    },
  },
  {
    id: "prod-google-pixel-9",
    categoryId: "pc-okostelefon",
    name: "Google Pixel 9 256GB",
    vendor: "Google",
    tier: "vezetoi",
    referencePrice: 369000,
    active: true,
    spec: {
      os: "Android",
      osVersion: "Android 16",
      cpu: "Google Tensor G4 (8 mag)",
      ram: "12 GB",
      storage: "256 GB",
      display: '6,3" Actua OLED, 120 Hz, 2700 nit',
      battery: "4700 mAh, 45 W töltés",
      ports: "USB-C 3.2, eSIM + nano SIM",
      warranty: "2 év gyártói garancia",
      features: ["Titan M2 biztonsági chip", "7 év frissítés", "IP68", "Android Enterprise", "MDM felügyelet"],
    },
  },
  {
    id: "prod-samsung-s25",
    categoryId: "pc-okostelefon",
    name: "Samsung Galaxy S25 256GB",
    vendor: "Samsung",
    tier: "vezetoi",
    referencePrice: 439000,
    active: true,
    spec: {
      os: "Android (One UI)",
      osVersion: "Android 15 / One UI 7",
      cpu: "Snapdragon 8 Elite for Galaxy (8 mag)",
      ram: "12 GB",
      storage: "256 GB",
      display: '6,2" Dynamic AMOLED 2X, 120 Hz, 2600 nit',
      battery: "4000 mAh, 25 W töltés",
      ports: "USB-C 3.2, eSIM + nano SIM",
      warranty: "2 év gyártói garancia",
      features: ["Samsung Knox Vault", "7 év frissítés", "IP68", "DeX asztali mód", "MDM felügyelet"],
    },
  },
  {
    id: "prod-iphone-16e",
    categoryId: "pc-okostelefon",
    name: "Apple iPhone 16e 128GB",
    vendor: "Apple",
    tier: "vezetoi",
    referencePrice: 289000,
    active: true,
    spec: {
      os: "iOS",
      osVersion: "18.6",
      cpu: "Apple A18",
      ram: "8 GB",
      storage: "128 GB",
      display: '6,1" Super Retina XDR OLED, 1200 nit',
      battery: "4005 mAh, kb. 26 óra videólejátszás",
      ports: "USB-C, eSIM",
      warranty: "2 év AppleCare",
      features: ["Face ID", "Secure Enclave", "MDM felügyelet", "IP68", "Apple Business Manager"],
    },
  },
  {
    id: "prod-samsung-s25-ultra",
    categoryId: "pc-okostelefon",
    name: "Samsung Galaxy S25 Ultra 512GB",
    vendor: "Samsung",
    tier: "felsovezetoi",
    referencePrice: 799000,
    active: true,
    spec: {
      os: "Android (One UI)",
      osVersion: "Android 15 / One UI 7",
      cpu: "Snapdragon 8 Elite for Galaxy (8 mag)",
      ram: "12 GB",
      storage: "512 GB",
      display: '6,9" Dynamic AMOLED 2X, 120 Hz, 2600 nit',
      battery: "5000 mAh, 45 W töltés",
      ports: "USB-C 3.2, eSIM + nano SIM",
      warranty: "2 év gyártói garancia",
      features: ["S Pen", "Titánkeret", "Samsung Knox Vault", "IP68", "Reprezentációs használatra alkalmas"],
    },
  },
  {
    id: "prod-iphone-16-pro-max",
    categoryId: "pc-okostelefon",
    name: "Apple iPhone 16 Pro Max 512GB",
    vendor: "Apple",
    tier: "felsovezetoi",
    referencePrice: 869000,
    active: true,
    spec: {
      os: "iOS",
      osVersion: "18.6",
      cpu: "Apple A18 Pro",
      ram: "8 GB",
      storage: "512 GB",
      display: '6,9" Super Retina XDR OLED, ProMotion 120 Hz, 2000 nit',
      battery: "4685 mAh, kb. 33 óra videólejátszás",
      ports: "USB-C (USB 3), eSIM",
      warranty: "2 év AppleCare",
      features: ["Face ID", "Titánház", "Secure Enclave", "MDM felügyelet", "Reprezentációs használatra alkalmas"],
    },
  },

  // ── Mobiltelefon (funkciótelefon) ──────────────────────────────────────
  {
    id: "prod-nokia-105-2023",
    categoryId: "pc-mobiltelefon",
    name: "Nokia 105 (2023)",
    vendor: "Nokia (HMD)",
    tier: "alkalmazotti",
    referencePrice: 9900,
    active: true,
    spec: {
      os: "S30+",
      osVersion: "gyári firmware",
      cpu: "Unisoc 6531F",
      ram: "4 MB",
      storage: "4 MB",
      display: '1,8" QQVGA',
      battery: "1000 mAh, kb. 18 nap készenlét",
      ports: "micro-USB, 3,5 mm jack",
      warranty: "2 év gyártói garancia",
      features: ["Dual SIM", "FM rádió", "Nagyon hosszú üzemidő", "Belépő tartalék készülék", "Nagy gombok"],
    },
  },
  {
    id: "prod-nokia-110-4g",
    categoryId: "pc-mobiltelefon",
    name: "Nokia 110 4G (2023)",
    vendor: "Nokia (HMD)",
    tier: "alkalmazotti",
    referencePrice: 16900,
    active: true,
    spec: {
      os: "S30+",
      osVersion: "gyári firmware",
      cpu: "Unisoc T107",
      ram: "48 MB",
      storage: "128 MB (microSD bővíthető)",
      display: '1,8" QQVGA',
      battery: "1450 mAh, kb. 15 nap készenlét",
      ports: "USB-C, 3,5 mm jack",
      warranty: "2 év gyártói garancia",
      features: ["4G VoLTE", "Dual SIM", "Bluetooth 5.0", "FM rádió", "Tartalék készüléknek"],
    },
  },
  {
    id: "prod-nokia-235-4g",
    categoryId: "pc-mobiltelefon",
    name: "Nokia 235 4G (2024)",
    vendor: "Nokia (HMD)",
    tier: "alkalmazotti",
    referencePrice: 24900,
    active: true,
    spec: {
      os: "S30+",
      osVersion: "gyári firmware",
      cpu: "Unisoc T107",
      ram: "64 MB",
      storage: "128 MB (microSD bővíthető)",
      display: '2,8" QVGA',
      battery: "1450 mAh, kb. 19 nap készenlét",
      ports: "USB-C, 3,5 mm jack",
      warranty: "2 év gyártói garancia",
      features: ["4G VoLTE", "Dual SIM", "Zseblámpa", "Bluetooth 5.0", "Portaszolgálati használatra"],
    },
  },
  {
    id: "prod-alcatel-2057",
    categoryId: "pc-mobiltelefon",
    name: "Alcatel 2057",
    vendor: "Alcatel",
    tier: "alkalmazotti",
    referencePrice: 11900,
    active: true,
    spec: {
      os: "gyári funkciótelefon rendszer",
      osVersion: "gyári firmware",
      cpu: "Spreadtrum SC6531E",
      ram: "4 MB",
      storage: "4 MB (microSD bővíthető)",
      display: '2,4" QVGA',
      battery: "970 mAh, kb. 14 nap készenlét",
      ports: "micro-USB, 3,5 mm jack",
      warranty: "2 év gyártói garancia",
      features: ["Dual SIM", "Nagy gombok", "FM rádió", "Zseblámpa", "Egyszerű kezelhetőség"],
    },
  },
  {
    id: "prod-energizer-e242s",
    categoryId: "pc-mobiltelefon",
    name: "Energizer E242S 4G",
    vendor: "Energizer",
    tier: "alkalmazotti",
    referencePrice: 21900,
    active: true,
    spec: {
      os: "KaiOS",
      osVersion: "2.5.4",
      cpu: "Unisoc T117",
      ram: "512 MB",
      storage: "4 GB (microSD bővíthető)",
      display: '2,8" QVGA',
      battery: "1500 mAh, kb. 12 nap készenlét",
      ports: "USB-C, 3,5 mm jack",
      warranty: "2 év gyártói garancia",
      features: ["4G VoLTE", "Wi-Fi hotspot", "Dual SIM", "KaiOS alkalmazások", "Ügyeleti használatra"],
    },
  },
  {
    id: "prod-nokia-2660-flip-2024",
    categoryId: "pc-mobiltelefon",
    name: "Nokia 2660 Flip 4G (fekete)",
    vendor: "Nokia (HMD)",
    tier: "vezetoi",
    referencePrice: 32900,
    active: true,
    spec: {
      os: "S30+",
      osVersion: "gyári firmware",
      cpu: "Unisoc T107",
      ram: "48 MB",
      storage: "128 MB (microSD bővíthető)",
      display: '2,8" QVGA belső + 1,77" külső',
      battery: "1450 mAh, kb. 20 nap készenlét",
      ports: "USB-C, 3,5 mm jack",
      warranty: "2 év gyártói garancia",
      features: ["4G VoLTE", "Vészhívó gomb", "Kihangosító", "Dual SIM", "Hallókészülék-kompatibilis"],
    },
  },
  {
    id: "prod-doro-6880",
    categoryId: "pc-mobiltelefon",
    name: "Doro 6880 szenior mobiltelefon",
    vendor: "Doro",
    tier: "vezetoi",
    referencePrice: 44900,
    active: true,
    spec: {
      os: "Doro OS",
      osVersion: "gyári firmware",
      cpu: "MediaTek MT6739",
      ram: "512 MB",
      storage: "4 GB (microSD bővíthető)",
      display: '2,8" QVGA',
      battery: "1350 mAh, kb. 12 nap készenlét",
      ports: "USB-C, 3,5 mm jack, töltőbölcső",
      warranty: "2 év gyártói garancia",
      features: ["4G VoLTE", "Vészhívó gomb", "Hallókészülék-kompatibilis", "Töltőbölcső", "Akadálymentes kezelés"],
    },
  },
  {
    id: "prod-cat-s22-flip",
    categoryId: "pc-mobiltelefon",
    name: "CAT S22 Flip strapabíró telefon",
    vendor: "Cat Phones",
    tier: "vezetoi",
    referencePrice: 59900,
    active: true,
    spec: {
      os: "Android Go",
      osVersion: "Android 11 (Go edition)",
      cpu: "Qualcomm QM215 (4 mag)",
      ram: "2 GB",
      storage: "16 GB (microSD bővíthető)",
      display: '2,8" érintőkijelző, QVGA',
      battery: "1350 mAh, kb. 8 nap készenlét",
      ports: "USB-C, 3,5 mm jack",
      warranty: "2 év gyártói garancia",
      features: ["IP68", "MIL-STD-810H", "Kesztyűs kezelés", "Android alkalmazások", "Műhelyhasználatra"],
    },
  },
  {
    id: "prod-punkt-mp02",
    categoryId: "pc-mobiltelefon",
    name: "Punkt. MP02 4G",
    vendor: "Punkt.",
    tier: "felsovezetoi",
    referencePrice: 129000,
    active: true,
    spec: {
      os: "Apostrophy AphyOS",
      osVersion: "gyári firmware",
      cpu: "Qualcomm 205 (2 mag)",
      ram: "512 MB",
      storage: "4 GB",
      display: '2" monokróm, magas kontraszt',
      battery: "1280 mAh, kb. 12 nap készenlét",
      ports: "USB-C",
      warranty: "2 év gyártói garancia",
      features: ["Titkosított kommunikáció (Pigeon)", "Wi-Fi hotspot", "Minimalista dizájn", "Reprezentációs használatra alkalmas", "Zavarásmentes munkavégzés"],
    },
  },
  {
    id: "prod-nokia-3210-2024",
    categoryId: "pc-mobiltelefon",
    name: "Nokia 3210 4G (2024)",
    vendor: "Nokia (HMD)",
    tier: "felsovezetoi",
    referencePrice: 34900,
    active: true,
    spec: {
      os: "S30+",
      osVersion: "gyári firmware",
      cpu: "Unisoc T107",
      ram: "64 MB",
      storage: "128 MB (microSD bővíthető)",
      display: '2,4" QVGA',
      battery: "1450 mAh, kb. 14 nap készenlét",
      ports: "USB-C, 3,5 mm jack",
      warranty: "2 év gyártói garancia",
      features: ["4G VoLTE", "Dual SIM", "Cloud böngésző", "Ikonikus dizájn", "Másodlagos készüléknek"],
    },
  },
];
