/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FejlesztesekRouteImport } from './routes/fejlesztesek'
import { Route as IgenyeimRouteImport } from './routes/igenyeim'
import { Route as MunkaterRouteImport } from './routes/munkater'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as SegitsegRouteImport } from './routes/segitseg'
import { Route as SzolgaltatasokRouteImport } from './routes/szolgaltatasok'
import { Route as UjIgenyRouteImport } from './routes/uj-igeny'
import { Route as IgenyIdRouteImport } from './routes/igeny.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FejlesztesekRoute = FejlesztesekRouteImport.update({
  id: '/fejlesztesek',
  path: '/fejlesztesek',
  getParentRoute: () => rootRouteImport,
} as any)
const IgenyeimRoute = IgenyeimRouteImport.update({
  id: '/igenyeim',
  path: '/igenyeim',
  getParentRoute: () => rootRouteImport,
} as any)
const MunkaterRoute = MunkaterRouteImport.update({
  id: '/munkater',
  path: '/munkater',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const SegitsegRoute = SegitsegRouteImport.update({
  id: '/segitseg',
  path: '/segitseg',
  getParentRoute: () => rootRouteImport,
} as any)
const SzolgaltatasokRoute = SzolgaltatasokRouteImport.update({
  id: '/szolgaltatasok',
  path: '/szolgaltatasok',
  getParentRoute: () => rootRouteImport,
} as any)
const UjIgenyRoute = UjIgenyRouteImport.update({
  id: '/uj-igeny',
  path: '/uj-igeny',
  getParentRoute: () => rootRouteImport,
} as any)
const IgenyIdRoute = IgenyIdRouteImport.update({
  id: '/igeny/$id',
  path: '/igeny/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fejlesztesek': typeof FejlesztesekRoute
  '/igenyeim': typeof IgenyeimRoute
  '/munkater': typeof MunkaterRoute
  '/profil': typeof ProfilRoute
  '/segitseg': typeof SegitsegRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
  '/uj-igeny': typeof UjIgenyRoute
  '/igeny/$id': typeof IgenyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fejlesztesek': typeof FejlesztesekRoute
  '/igenyeim': typeof IgenyeimRoute
  '/munkater': typeof MunkaterRoute
  '/profil': typeof ProfilRoute
  '/segitseg': typeof SegitsegRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
  '/uj-igeny': typeof UjIgenyRoute
  '/igeny/$id': typeof IgenyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fejlesztesek': typeof FejlesztesekRoute
  '/igenyeim': typeof IgenyeimRoute
  '/munkater': typeof MunkaterRoute
  '/profil': typeof ProfilRoute
  '/segitseg': typeof SegitsegRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
  '/uj-igeny': typeof UjIgenyRoute
  '/igeny/$id': typeof IgenyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fejlesztesek'
    | '/igenyeim'
    | '/munkater'
    | '/profil'
    | '/segitseg'
    | '/szolgaltatasok'
    | '/uj-igeny'
    | '/igeny/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fejlesztesek'
    | '/igenyeim'
    | '/munkater'
    | '/profil'
    | '/segitseg'
    | '/szolgaltatasok'
    | '/uj-igeny'
    | '/igeny/$id'
  id:
    | '__root__'
    | '/'
    | '/fejlesztesek'
    | '/igenyeim'
    | '/munkater'
    | '/profil'
    | '/segitseg'
    | '/szolgaltatasok'
    | '/uj-igeny'
    | '/igeny/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FejlesztesekRoute: typeof FejlesztesekRoute
  IgenyeimRoute: typeof IgenyeimRoute
  MunkaterRoute: typeof MunkaterRoute
  ProfilRoute: typeof ProfilRoute
  SegitsegRoute: typeof SegitsegRoute
  SzolgaltatasokRoute: typeof SzolgaltatasokRoute
  UjIgenyRoute: typeof UjIgenyRoute
  IgenyIdRoute: typeof IgenyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fejlesztesek': {
      id: '/fejlesztesek'
      path: '/fejlesztesek'
      fullPath: '/fejlesztesek'
      preLoaderRoute: typeof FejlesztesekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/igenyeim': {
      id: '/igenyeim'
      path: '/igenyeim'
      fullPath: '/igenyeim'
      preLoaderRoute: typeof IgenyeimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/munkater': {
      id: '/munkater'
      path: '/munkater'
      fullPath: '/munkater'
      preLoaderRoute: typeof MunkaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segitseg': {
      id: '/segitseg'
      path: '/segitseg'
      fullPath: '/segitseg'
      preLoaderRoute: typeof SegitsegRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/szolgaltatasok': {
      id: '/szolgaltatasok'
      path: '/szolgaltatasok'
      fullPath: '/szolgaltatasok'
      preLoaderRoute: typeof SzolgaltatasokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uj-igeny': {
      id: '/uj-igeny'
      path: '/uj-igeny'
      fullPath: '/uj-igeny'
      preLoaderRoute: typeof UjIgenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/igeny/$id': {
      id: '/igeny/$id'
      path: '/igeny/$id'
      fullPath: '/igeny/$id'
      preLoaderRoute: typeof IgenyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FejlesztesekRoute: FejlesztesekRoute,
  IgenyeimRoute: IgenyeimRoute,
  MunkaterRoute: MunkaterRoute,
  ProfilRoute: ProfilRoute,
  SegitsegRoute: SegitsegRoute,
  SzolgaltatasokRoute: SzolgaltatasokRoute,
  UjIgenyRoute: UjIgenyRoute,
  IgenyIdRoute: IgenyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
