/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminisztracioRouteImport } from './routes/adminisztracio'
import { Route as BeszerzesiTervRouteImport } from './routes/beszerzesi-terv'
import { Route as EletciklusElorejelzesRouteImport } from './routes/eletciklus-elorejelzes'
import { Route as EszkozkataszterRouteImport } from './routes/eszkozkataszter'
import { Route as FejlesztesekRouteImport } from './routes/fejlesztesek'
import { Route as FelelossegekRouteImport } from './routes/felelossegek'
import { Route as IgenyeimRouteImport } from './routes/igenyeim'
import { Route as LeltarRouteImport } from './routes/leltar'
import { Route as MunkaterRouteImport } from './routes/munkater'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as SegitsegRouteImport } from './routes/segitseg'
import { Route as SzolgaltatasokRouteImport } from './routes/szolgaltatasok'
import { Route as UjIgenyRouteImport } from './routes/uj-igeny'
import { Route as VezetoiAttekintesRouteImport } from './routes/vezetoi-attekintes'
import { Route as EszkozIdRouteImport } from './routes/eszkoz.$id'
import { Route as IgenyIdRouteImport } from './routes/igeny.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminisztracioRoute = AdminisztracioRouteImport.update({
  id: '/adminisztracio',
  path: '/adminisztracio',
  getParentRoute: () => rootRouteImport,
} as any)
const BeszerzesiTervRoute = BeszerzesiTervRouteImport.update({
  id: '/beszerzesi-terv',
  path: '/beszerzesi-terv',
  getParentRoute: () => rootRouteImport,
} as any)
const EletciklusElorejelzesRoute = EletciklusElorejelzesRouteImport.update({
  id: '/eletciklus-elorejelzes',
  path: '/eletciklus-elorejelzes',
  getParentRoute: () => rootRouteImport,
} as any)
const EszkozkataszterRoute = EszkozkataszterRouteImport.update({
  id: '/eszkozkataszter',
  path: '/eszkozkataszter',
  getParentRoute: () => rootRouteImport,
} as any)
const FejlesztesekRoute = FejlesztesekRouteImport.update({
  id: '/fejlesztesek',
  path: '/fejlesztesek',
  getParentRoute: () => rootRouteImport,
} as any)
const FelelossegekRoute = FelelossegekRouteImport.update({
  id: '/felelossegek',
  path: '/felelossegek',
  getParentRoute: () => rootRouteImport,
} as any)
const IgenyeimRoute = IgenyeimRouteImport.update({
  id: '/igenyeim',
  path: '/igenyeim',
  getParentRoute: () => rootRouteImport,
} as any)
const LeltarRoute = LeltarRouteImport.update({
  id: '/leltar',
  path: '/leltar',
  getParentRoute: () => rootRouteImport,
} as any)
const MunkaterRoute = MunkaterRouteImport.update({
  id: '/munkater',
  path: '/munkater',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const SegitsegRoute = SegitsegRouteImport.update({
  id: '/segitseg',
  path: '/segitseg',
  getParentRoute: () => rootRouteImport,
} as any)
const SzolgaltatasokRoute = SzolgaltatasokRouteImport.update({
  id: '/szolgaltatasok',
  path: '/szolgaltatasok',
  getParentRoute: () => rootRouteImport,
} as any)
const UjIgenyRoute = UjIgenyRouteImport.update({
  id: '/uj-igeny',
  path: '/uj-igeny',
  getParentRoute: () => rootRouteImport,
} as any)
const VezetoiAttekintesRoute = VezetoiAttekintesRouteImport.update({
  id: '/vezetoi-attekintes',
  path: '/vezetoi-attekintes',
  getParentRoute: () => rootRouteImport,
} as any)
const EszkozIdRoute = EszkozIdRouteImport.update({
  id: '/eszkoz/$id',
  path: '/eszkoz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IgenyIdRoute = IgenyIdRouteImport.update({
  id: '/igeny/$id',
  path: '/igeny/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adminisztracio': typeof AdminisztracioRoute
  '/beszerzesi-terv': typeof BeszerzesiTervRoute
  '/eletciklus-elorejelzes': typeof EletciklusElorejelzesRoute
  '/eszkozkataszter': typeof EszkozkataszterRoute
  '/fejlesztesek': typeof FejlesztesekRoute
  '/felelossegek': typeof FelelossegekRoute
  '/igenyeim': typeof IgenyeimRoute
  '/leltar': typeof LeltarRoute
  '/munkater': typeof MunkaterRoute
  '/portfolio': typeof PortfolioRoute
  '/profil': typeof ProfilRoute
  '/segitseg': typeof SegitsegRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
  '/uj-igeny': typeof UjIgenyRoute
  '/vezetoi-attekintes': typeof VezetoiAttekintesRoute
  '/eszkoz/$id': typeof EszkozIdRoute
  '/igeny/$id': typeof IgenyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adminisztracio': typeof AdminisztracioRoute
  '/beszerzesi-terv': typeof BeszerzesiTervRoute
  '/eletciklus-elorejelzes': typeof EletciklusElorejelzesRoute
  '/eszkozkataszter': typeof EszkozkataszterRoute
  '/fejlesztesek': typeof FejlesztesekRoute
  '/felelossegek': typeof FelelossegekRoute
  '/igenyeim': typeof IgenyeimRoute
  '/leltar': typeof LeltarRoute
  '/munkater': typeof MunkaterRoute
  '/portfolio': typeof PortfolioRoute
  '/profil': typeof ProfilRoute
  '/segitseg': typeof SegitsegRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
  '/uj-igeny': typeof UjIgenyRoute
  '/vezetoi-attekintes': typeof VezetoiAttekintesRoute
  '/eszkoz/$id': typeof EszkozIdRoute
  '/igeny/$id': typeof IgenyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adminisztracio': typeof AdminisztracioRoute
  '/beszerzesi-terv': typeof BeszerzesiTervRoute
  '/eletciklus-elorejelzes': typeof EletciklusElorejelzesRoute
  '/eszkozkataszter': typeof EszkozkataszterRoute
  '/fejlesztesek': typeof FejlesztesekRoute
  '/felelossegek': typeof FelelossegekRoute
  '/igenyeim': typeof IgenyeimRoute
  '/leltar': typeof LeltarRoute
  '/munkater': typeof MunkaterRoute
  '/portfolio': typeof PortfolioRoute
  '/profil': typeof ProfilRoute
  '/segitseg': typeof SegitsegRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
  '/uj-igeny': typeof UjIgenyRoute
  '/vezetoi-attekintes': typeof VezetoiAttekintesRoute
  '/eszkoz/$id': typeof EszkozIdRoute
  '/igeny/$id': typeof IgenyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adminisztracio'
    | '/beszerzesi-terv'
    | '/eletciklus-elorejelzes'
    | '/eszkozkataszter'
    | '/fejlesztesek'
    | '/felelossegek'
    | '/igenyeim'
    | '/leltar'
    | '/munkater'
    | '/portfolio'
    | '/profil'
    | '/segitseg'
    | '/szolgaltatasok'
    | '/uj-igeny'
    | '/vezetoi-attekintes'
    | '/eszkoz/$id'
    | '/igeny/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adminisztracio'
    | '/beszerzesi-terv'
    | '/eletciklus-elorejelzes'
    | '/eszkozkataszter'
    | '/fejlesztesek'
    | '/felelossegek'
    | '/igenyeim'
    | '/leltar'
    | '/munkater'
    | '/portfolio'
    | '/profil'
    | '/segitseg'
    | '/szolgaltatasok'
    | '/uj-igeny'
    | '/vezetoi-attekintes'
    | '/eszkoz/$id'
    | '/igeny/$id'
  id:
    | '__root__'
    | '/'
    | '/adminisztracio'
    | '/beszerzesi-terv'
    | '/eletciklus-elorejelzes'
    | '/eszkozkataszter'
    | '/fejlesztesek'
    | '/felelossegek'
    | '/igenyeim'
    | '/leltar'
    | '/munkater'
    | '/portfolio'
    | '/profil'
    | '/segitseg'
    | '/szolgaltatasok'
    | '/uj-igeny'
    | '/vezetoi-attekintes'
    | '/eszkoz/$id'
    | '/igeny/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminisztracioRoute: typeof AdminisztracioRoute
  BeszerzesiTervRoute: typeof BeszerzesiTervRoute
  EletciklusElorejelzesRoute: typeof EletciklusElorejelzesRoute
  EszkozkataszterRoute: typeof EszkozkataszterRoute
  FejlesztesekRoute: typeof FejlesztesekRoute
  FelelossegekRoute: typeof FelelossegekRoute
  IgenyeimRoute: typeof IgenyeimRoute
  LeltarRoute: typeof LeltarRoute
  MunkaterRoute: typeof MunkaterRoute
  PortfolioRoute: typeof PortfolioRoute
  ProfilRoute: typeof ProfilRoute
  SegitsegRoute: typeof SegitsegRoute
  SzolgaltatasokRoute: typeof SzolgaltatasokRoute
  UjIgenyRoute: typeof UjIgenyRoute
  VezetoiAttekintesRoute: typeof VezetoiAttekintesRoute
  EszkozIdRoute: typeof EszkozIdRoute
  IgenyIdRoute: typeof IgenyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminisztracio': {
      id: '/adminisztracio'
      path: '/adminisztracio'
      fullPath: '/adminisztracio'
      preLoaderRoute: typeof AdminisztracioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beszerzesi-terv': {
      id: '/beszerzesi-terv'
      path: '/beszerzesi-terv'
      fullPath: '/beszerzesi-terv'
      preLoaderRoute: typeof BeszerzesiTervRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eletciklus-elorejelzes': {
      id: '/eletciklus-elorejelzes'
      path: '/eletciklus-elorejelzes'
      fullPath: '/eletciklus-elorejelzes'
      preLoaderRoute: typeof EletciklusElorejelzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eszkozkataszter': {
      id: '/eszkozkataszter'
      path: '/eszkozkataszter'
      fullPath: '/eszkozkataszter'
      preLoaderRoute: typeof EszkozkataszterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fejlesztesek': {
      id: '/fejlesztesek'
      path: '/fejlesztesek'
      fullPath: '/fejlesztesek'
      preLoaderRoute: typeof FejlesztesekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/felelossegek': {
      id: '/felelossegek'
      path: '/felelossegek'
      fullPath: '/felelossegek'
      preLoaderRoute: typeof FelelossegekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/igenyeim': {
      id: '/igenyeim'
      path: '/igenyeim'
      fullPath: '/igenyeim'
      preLoaderRoute: typeof IgenyeimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leltar': {
      id: '/leltar'
      path: '/leltar'
      fullPath: '/leltar'
      preLoaderRoute: typeof LeltarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/munkater': {
      id: '/munkater'
      path: '/munkater'
      fullPath: '/munkater'
      preLoaderRoute: typeof MunkaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segitseg': {
      id: '/segitseg'
      path: '/segitseg'
      fullPath: '/segitseg'
      preLoaderRoute: typeof SegitsegRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/szolgaltatasok': {
      id: '/szolgaltatasok'
      path: '/szolgaltatasok'
      fullPath: '/szolgaltatasok'
      preLoaderRoute: typeof SzolgaltatasokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uj-igeny': {
      id: '/uj-igeny'
      path: '/uj-igeny'
      fullPath: '/uj-igeny'
      preLoaderRoute: typeof UjIgenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vezetoi-attekintes': {
      id: '/vezetoi-attekintes'
      path: '/vezetoi-attekintes'
      fullPath: '/vezetoi-attekintes'
      preLoaderRoute: typeof VezetoiAttekintesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eszkoz/$id': {
      id: '/eszkoz/$id'
      path: '/eszkoz/$id'
      fullPath: '/eszkoz/$id'
      preLoaderRoute: typeof EszkozIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/igeny/$id': {
      id: '/igeny/$id'
      path: '/igeny/$id'
      fullPath: '/igeny/$id'
      preLoaderRoute: typeof IgenyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminisztracioRoute: AdminisztracioRoute,
  BeszerzesiTervRoute: BeszerzesiTervRoute,
  EletciklusElorejelzesRoute: EletciklusElorejelzesRoute,
  EszkozkataszterRoute: EszkozkataszterRoute,
  FejlesztesekRoute: FejlesztesekRoute,
  FelelossegekRoute: FelelossegekRoute,
  IgenyeimRoute: IgenyeimRoute,
  LeltarRoute: LeltarRoute,
  MunkaterRoute: MunkaterRoute,
  PortfolioRoute: PortfolioRoute,
  ProfilRoute: ProfilRoute,
  SegitsegRoute: SegitsegRoute,
  SzolgaltatasokRoute: SzolgaltatasokRoute,
  UjIgenyRoute: UjIgenyRoute,
  VezetoiAttekintesRoute: VezetoiAttekintesRoute,
  EszkozIdRoute: EszkozIdRoute,
  IgenyIdRoute: IgenyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
