/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminisztracioRouteImport } from './routes/adminisztracio'
import { Route as BeszerzesiTervRouteImport } from './routes/beszerzesi-terv'
import { Route as DekaniAttekintesRouteImport } from './routes/dekani-attekintes'
import { Route as EletciklusElorejelzesRouteImport } from './routes/eletciklus-elorejelzes'
import { Route as EszkozkataszterRouteImport } from './routes/eszkozkataszter'
import { Route as FejlesztesekRouteImport } from './routes/fejlesztesek'
import { Route as FelelossegekRouteImport } from './routes/felelossegek'
import { Route as IgenyeimRouteImport } from './routes/igenyeim'
import { Route as JogosultsagokRouteImport } from './routes/jogosultsagok'
import { Route as JovahagyasokRouteImport } from './routes/jovahagyasok'
import { Route as LeltarRouteImport } from './routes/leltar'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MunkaterRouteImport } from './routes/munkater'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as SegitsegRouteImport } from './routes/segitseg'
import { Route as SzolgaltatasokRouteImport } from './routes/szolgaltatasok'
import { Route as UjIgenyRouteImport } from './routes/uj-igeny'
import { Route as VezetoiAttekintesRouteImport } from './routes/vezetoi-attekintes'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as EszkozIdRouteImport } from './routes/eszkoz.$id'
import { Route as IgenyIdRouteImport } from './routes/igeny.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminisztracioRoute = AdminisztracioRouteImport.update({
  id: '/adminisztracio',
  path: '/adminisztracio',
  getParentRoute: () => rootRouteImport,
} as any)
const BeszerzesiTervRoute = BeszerzesiTervRouteImport.update({
  id: '/beszerzesi-terv',
  path: '/beszerzesi-terv',
  getParentRoute: () => rootRouteImport,
} as any)
const DekaniAttekintesRoute = DekaniAttekintesRouteImport.update({
  id: '/dekani-attekintes',
  path: '/dekani-attekintes',
  getParentRoute: () => rootRouteImport,
} as any)
const EletciklusElorejelzesRoute = EletciklusElorejelzesRouteImport.update({
  id: '/eletciklus-elorejelzes',
  path: '/eletciklus-elorejelzes',
  getParentRoute: () => rootRouteImport,
} as any)
const EszkozkataszterRoute = EszkozkataszterRouteImport.update({
  id: '/eszkozkataszter',
  path: '/eszkozkataszter',
  getParentRoute: () => rootRouteImport,
} as any)
const FejlesztesekRoute = FejlesztesekRouteImport.update({
  id: '/fejlesztesek',
  path: '/fejlesztesek',
  getParentRoute: () => rootRouteImport,
} as any)
const FelelossegekRoute = FelelossegekRouteImport.update({
  id: '/felelossegek',
  path: '/felelossegek',
  getParentRoute: () => rootRouteImport,
} as any)
const IgenyeimRoute = IgenyeimRouteImport.update({
  id: '/igenyeim',
  path: '/igenyeim',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosultsagokRoute = JogosultsagokRouteImport.update({
  id: '/jogosultsagok',
  path: '/jogosultsagok',
  getParentRoute: () => rootRouteImport,
} as any)
const JovahagyasokRoute = JovahagyasokRouteImport.update({
  id: '/jovahagyasok',
  path: '/jovahagyasok',
  getParentRoute: () => rootRouteImport,
} as any)
const LeltarRoute = LeltarRouteImport.update({
  id: '/leltar',
  path: '/leltar',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MunkaterRoute = MunkaterRouteImport.update({
  id: '/munkater',
  path: '/munkater',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const SegitsegRoute = SegitsegRouteImport.update({
  id: '/segitseg',
  path: '/segitseg',
  getParentRoute: () => rootRouteImport,
} as any)
const SzolgaltatasokRoute = SzolgaltatasokRouteImport.update({
  id: '/szolgaltatasok',
  path: '/szolgaltatasok',
  getParentRoute: () => rootRouteImport,
} as any)
const UjIgenyRoute = UjIgenyRouteImport.update({
  id: '/uj-igeny',
  path: '/uj-igeny',
  getParentRoute: () => rootRouteImport,
} as any)
const VezetoiAttekintesRoute = VezetoiAttekintesRouteImport.update({
  id: '/vezetoi-attekintes',
  path: '/vezetoi-attekintes',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const EszkozIdRoute = EszkozIdRouteImport.update({
  id: '/eszkoz/$id',
  path: '/eszkoz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IgenyIdRoute = IgenyIdRouteImport.update({
  id: '/igeny/$id',
  path: '/igeny/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adminisztracio': typeof AdminisztracioRoute
  '/beszerzesi-terv': typeof BeszerzesiTervRoute
  '/dekani-attekintes': typeof DekaniAttekintesRoute
  '/eletciklus-elorejelzes': typeof EletciklusElorejelzesRoute
  '/eszkozkataszter': typeof EszkozkataszterRoute
  '/fejlesztesek': typeof FejlesztesekRoute
  '/felelossegek': typeof FelelossegekRoute
  '/igenyeim': typeof IgenyeimRoute
  '/jogosultsagok': typeof JogosultsagokRoute
  '/jovahagyasok': typeof JovahagyasokRoute
  '/leltar': typeof LeltarRoute
  '/mcp': typeof McpRoute
  '/munkater': typeof MunkaterRoute
  '/portfolio': typeof PortfolioRoute
  '/profil': typeof ProfilRoute
  '/segitseg': typeof SegitsegRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
  '/uj-igeny': typeof UjIgenyRoute
  '/vezetoi-attekintes': typeof VezetoiAttekintesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/eszkoz/$id': typeof EszkozIdRoute
  '/igeny/$id': typeof IgenyIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adminisztracio': typeof AdminisztracioRoute
  '/beszerzesi-terv': typeof BeszerzesiTervRoute
  '/dekani-attekintes': typeof DekaniAttekintesRoute
  '/eletciklus-elorejelzes': typeof EletciklusElorejelzesRoute
  '/eszkozkataszter': typeof EszkozkataszterRoute
  '/fejlesztesek': typeof FejlesztesekRoute
  '/felelossegek': typeof FelelossegekRoute
  '/igenyeim': typeof IgenyeimRoute
  '/jogosultsagok': typeof JogosultsagokRoute
  '/jovahagyasok': typeof JovahagyasokRoute
  '/leltar': typeof LeltarRoute
  '/mcp': typeof McpRoute
  '/munkater': typeof MunkaterRoute
  '/portfolio': typeof PortfolioRoute
  '/profil': typeof ProfilRoute
  '/segitseg': typeof SegitsegRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
  '/uj-igeny': typeof UjIgenyRoute
  '/vezetoi-attekintes': typeof VezetoiAttekintesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/eszkoz/$id': typeof EszkozIdRoute
  '/igeny/$id': typeof IgenyIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adminisztracio': typeof AdminisztracioRoute
  '/beszerzesi-terv': typeof BeszerzesiTervRoute
  '/dekani-attekintes': typeof DekaniAttekintesRoute
  '/eletciklus-elorejelzes': typeof EletciklusElorejelzesRoute
  '/eszkozkataszter': typeof EszkozkataszterRoute
  '/fejlesztesek': typeof FejlesztesekRoute
  '/felelossegek': typeof FelelossegekRoute
  '/igenyeim': typeof IgenyeimRoute
  '/jogosultsagok': typeof JogosultsagokRoute
  '/jovahagyasok': typeof JovahagyasokRoute
  '/leltar': typeof LeltarRoute
  '/mcp': typeof McpRoute
  '/munkater': typeof MunkaterRoute
  '/portfolio': typeof PortfolioRoute
  '/profil': typeof ProfilRoute
  '/segitseg': typeof SegitsegRoute
  '/szolgaltatasok': typeof SzolgaltatasokRoute
  '/uj-igeny': typeof UjIgenyRoute
  '/vezetoi-attekintes': typeof VezetoiAttekintesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/eszkoz/$id': typeof EszkozIdRoute
  '/igeny/$id': typeof IgenyIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adminisztracio'
    | '/beszerzesi-terv'
    | '/dekani-attekintes'
    | '/eletciklus-elorejelzes'
    | '/eszkozkataszter'
    | '/fejlesztesek'
    | '/felelossegek'
    | '/igenyeim'
    | '/jogosultsagok'
    | '/jovahagyasok'
    | '/leltar'
    | '/mcp'
    | '/munkater'
    | '/portfolio'
    | '/profil'
    | '/segitseg'
    | '/szolgaltatasok'
    | '/uj-igeny'
    | '/vezetoi-attekintes'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/eszkoz/$id'
    | '/igeny/$id'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adminisztracio'
    | '/beszerzesi-terv'
    | '/dekani-attekintes'
    | '/eletciklus-elorejelzes'
    | '/eszkozkataszter'
    | '/fejlesztesek'
    | '/felelossegek'
    | '/igenyeim'
    | '/jogosultsagok'
    | '/jovahagyasok'
    | '/leltar'
    | '/mcp'
    | '/munkater'
    | '/portfolio'
    | '/profil'
    | '/segitseg'
    | '/szolgaltatasok'
    | '/uj-igeny'
    | '/vezetoi-attekintes'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/eszkoz/$id'
    | '/igeny/$id'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/adminisztracio'
    | '/beszerzesi-terv'
    | '/dekani-attekintes'
    | '/eletciklus-elorejelzes'
    | '/eszkozkataszter'
    | '/fejlesztesek'
    | '/felelossegek'
    | '/igenyeim'
    | '/jogosultsagok'
    | '/jovahagyasok'
    | '/leltar'
    | '/mcp'
    | '/munkater'
    | '/portfolio'
    | '/profil'
    | '/segitseg'
    | '/szolgaltatasok'
    | '/uj-igeny'
    | '/vezetoi-attekintes'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/eszkoz/$id'
    | '/igeny/$id'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminisztracioRoute: typeof AdminisztracioRoute
  BeszerzesiTervRoute: typeof BeszerzesiTervRoute
  DekaniAttekintesRoute: typeof DekaniAttekintesRoute
  EletciklusElorejelzesRoute: typeof EletciklusElorejelzesRoute
  EszkozkataszterRoute: typeof EszkozkataszterRoute
  FejlesztesekRoute: typeof FejlesztesekRoute
  FelelossegekRoute: typeof FelelossegekRoute
  IgenyeimRoute: typeof IgenyeimRoute
  JogosultsagokRoute: typeof JogosultsagokRoute
  JovahagyasokRoute: typeof JovahagyasokRoute
  LeltarRoute: typeof LeltarRoute
  McpRoute: typeof McpRoute
  MunkaterRoute: typeof MunkaterRoute
  PortfolioRoute: typeof PortfolioRoute
  ProfilRoute: typeof ProfilRoute
  SegitsegRoute: typeof SegitsegRoute
  SzolgaltatasokRoute: typeof SzolgaltatasokRoute
  UjIgenyRoute: typeof UjIgenyRoute
  VezetoiAttekintesRoute: typeof VezetoiAttekintesRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  EszkozIdRoute: typeof EszkozIdRoute
  IgenyIdRoute: typeof IgenyIdRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminisztracio': {
      id: '/adminisztracio'
      path: '/adminisztracio'
      fullPath: '/adminisztracio'
      preLoaderRoute: typeof AdminisztracioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beszerzesi-terv': {
      id: '/beszerzesi-terv'
      path: '/beszerzesi-terv'
      fullPath: '/beszerzesi-terv'
      preLoaderRoute: typeof BeszerzesiTervRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dekani-attekintes': {
      id: '/dekani-attekintes'
      path: '/dekani-attekintes'
      fullPath: '/dekani-attekintes'
      preLoaderRoute: typeof DekaniAttekintesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eletciklus-elorejelzes': {
      id: '/eletciklus-elorejelzes'
      path: '/eletciklus-elorejelzes'
      fullPath: '/eletciklus-elorejelzes'
      preLoaderRoute: typeof EletciklusElorejelzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eszkozkataszter': {
      id: '/eszkozkataszter'
      path: '/eszkozkataszter'
      fullPath: '/eszkozkataszter'
      preLoaderRoute: typeof EszkozkataszterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fejlesztesek': {
      id: '/fejlesztesek'
      path: '/fejlesztesek'
      fullPath: '/fejlesztesek'
      preLoaderRoute: typeof FejlesztesekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/felelossegek': {
      id: '/felelossegek'
      path: '/felelossegek'
      fullPath: '/felelossegek'
      preLoaderRoute: typeof FelelossegekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/igenyeim': {
      id: '/igenyeim'
      path: '/igenyeim'
      fullPath: '/igenyeim'
      preLoaderRoute: typeof IgenyeimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogosultsagok': {
      id: '/jogosultsagok'
      path: '/jogosultsagok'
      fullPath: '/jogosultsagok'
      preLoaderRoute: typeof JogosultsagokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jovahagyasok': {
      id: '/jovahagyasok'
      path: '/jovahagyasok'
      fullPath: '/jovahagyasok'
      preLoaderRoute: typeof JovahagyasokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leltar': {
      id: '/leltar'
      path: '/leltar'
      fullPath: '/leltar'
      preLoaderRoute: typeof LeltarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/munkater': {
      id: '/munkater'
      path: '/munkater'
      fullPath: '/munkater'
      preLoaderRoute: typeof MunkaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segitseg': {
      id: '/segitseg'
      path: '/segitseg'
      fullPath: '/segitseg'
      preLoaderRoute: typeof SegitsegRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/szolgaltatasok': {
      id: '/szolgaltatasok'
      path: '/szolgaltatasok'
      fullPath: '/szolgaltatasok'
      preLoaderRoute: typeof SzolgaltatasokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uj-igeny': {
      id: '/uj-igeny'
      path: '/uj-igeny'
      fullPath: '/uj-igeny'
      preLoaderRoute: typeof UjIgenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vezetoi-attekintes': {
      id: '/vezetoi-attekintes'
      path: '/vezetoi-attekintes'
      fullPath: '/vezetoi-attekintes'
      preLoaderRoute: typeof VezetoiAttekintesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eszkoz/$id': {
      id: '/eszkoz/$id'
      path: '/eszkoz/$id'
      fullPath: '/eszkoz/$id'
      preLoaderRoute: typeof EszkozIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/igeny/$id': {
      id: '/igeny/$id'
      path: '/igeny/$id'
      fullPath: '/igeny/$id'
      preLoaderRoute: typeof IgenyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminisztracioRoute: AdminisztracioRoute,
  BeszerzesiTervRoute: BeszerzesiTervRoute,
  DekaniAttekintesRoute: DekaniAttekintesRoute,
  EletciklusElorejelzesRoute: EletciklusElorejelzesRoute,
  EszkozkataszterRoute: EszkozkataszterRoute,
  FejlesztesekRoute: FejlesztesekRoute,
  FelelossegekRoute: FelelossegekRoute,
  IgenyeimRoute: IgenyeimRoute,
  JogosultsagokRoute: JogosultsagokRoute,
  JovahagyasokRoute: JovahagyasokRoute,
  LeltarRoute: LeltarRoute,
  McpRoute: McpRoute,
  MunkaterRoute: MunkaterRoute,
  PortfolioRoute: PortfolioRoute,
  ProfilRoute: ProfilRoute,
  SegitsegRoute: SegitsegRoute,
  SzolgaltatasokRoute: SzolgaltatasokRoute,
  UjIgenyRoute: UjIgenyRoute,
  VezetoiAttekintesRoute: VezetoiAttekintesRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  EszkozIdRoute: EszkozIdRoute,
  IgenyIdRoute: IgenyIdRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
